//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.26 at 11:00:00 ���� CST 
//

package com.cneport.ecss.exchange.service.cebentity;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="totalLogisticsNo">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="24"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="subLogisticsNo">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="24"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="logisticsNo">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="24"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="billType">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="logisticsCode">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="logisticsName">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="logisticsStatus">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="deliverDate">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="14"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="failReason">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ieType">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "totalLogisticsNo", "subLogisticsNo",
	"logisticsNo", "billType", "logisticsCode", "logisticsName",
	"logisticsStatus", "deliverDate", "failReason", "ieType" ,"trafMode",
	"customsCode", "voyageNo", "billNo", "note","accessType","appUid",
    "appUname","shipName","appTime","appStatus","appType"})
@XmlRootElement(name = "LogisticsStatus")
public class LogisticsStatus {

    @XmlElement(required = true)
    protected String totalLogisticsNo;
    @XmlElement(required = true)
    protected String subLogisticsNo;
    @XmlElement(required = true)
    protected String logisticsNo;
    @XmlElement(required = true)
    protected String billType;
    @XmlElement(required = true)
    protected String logisticsCode;
    @XmlElement(required = true)
    protected String logisticsName;
    @XmlElement(required = true)
    protected String logisticsStatus;
    @XmlElement(required = true)
    protected String deliverDate;
    @XmlElement(required = true)
    protected String failReason;
    @XmlElement(required = true)
    protected String ieType;
    
    public String getTrafMode() {
		return trafMode;
	}

	public void setTrafMode(String trafMode) {
		this.trafMode = trafMode;
	}

	public String getCustomsCode() {
		return customsCode;
	}

	public void setCustomsCode(String customsCode) {
		this.customsCode = customsCode;
	}

	public String getVoyageNo() {
		return voyageNo;
	}

	public void setVoyageNo(String voyageNo) {
		this.voyageNo = voyageNo;
	}

	public String getBillNo() {
		return billNo;
	}

	public void setBillNo(String billNo) {
		this.billNo = billNo;
	}

	public String getNote() {
		return note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public String getAccessType() {
		return accessType;
	}

	public void setAccessType(String accessType) {
		this.accessType = accessType;
	}

	public String getAppUid() {
		return appUid;
	}

	public void setAppUid(String appUid) {
		this.appUid = appUid;
	}

	public String getAppUname() {
		return appUname;
	}

	public void setAppUname(String appUname) {
		this.appUname = appUname;
	}

	@XmlElement(required = true)
    protected String trafMode;
    @XmlElement(required = true)
    protected String customsCode;
    @XmlElement(required = true)
    protected String voyageNo;
    @XmlElement(required = true)
    protected String billNo;
    @XmlElement(required = true)
    protected String note;
    @XmlElement(required = true)
    protected String accessType;
    @XmlElement(required = true)
    protected String appUid;
    @XmlElement(required = true)
    protected String appUname;
    @XmlElement(required = true)
    protected String shipName;
    public String getShipName() {
		return shipName;
	}
    @XmlElement(required = true)
    protected String appTime;
    public void setAppTime(String appTime) {
		this.appTime = appTime;
	}

	public void setAppStatus(String appStatus) {
		this.appStatus = appStatus;
	}

	public String getAppTime() {
		return appTime;
    }
    @XmlElement(required = true)
    protected String appStatus;
    public String getAppStatus() {
		return appStatus;
    }
    @XmlElement(required = true)
    protected String appType;
    public String getAppType() {
		return appType;
    }
    
	public void setAppType(String appType) {
		this.appType = appType;
	}

	public void setShipName(String shipName) {
		this.shipName = shipName;
	}

	/**
     * Gets the value of the totalLogisticsNo property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTotalLogisticsNo() {
	return totalLogisticsNo;
    }

    /**
     * Sets the value of the totalLogisticsNo property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setTotalLogisticsNo(String value) {
	this.totalLogisticsNo = value;
    }

    /**
     * Gets the value of the subLogisticsNo property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSubLogisticsNo() {
	return subLogisticsNo;
    }

    /**
     * Sets the value of the subLogisticsNo property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setSubLogisticsNo(String value) {
	this.subLogisticsNo = value;
    }

    /**
     * Gets the value of the logisticsNo property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getLogisticsNo() {
	return logisticsNo;
    }

    /**
     * Sets the value of the logisticsNo property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setLogisticsNo(String value) {
	this.logisticsNo = value;
    }

    /**
     * Gets the value of the billType property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getBillType() {
	return billType;
    }

    /**
     * Sets the value of the billType property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setBillType(String value) {
	this.billType = value;
    }

    /**
     * Gets the value of the logisticsCode property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getLogisticsCode() {
	return logisticsCode;
    }

    /**
     * Sets the value of the logisticsCode property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setLogisticsCode(String value) {
	this.logisticsCode = value;
    }

    /**
     * Gets the value of the logisticsName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getLogisticsName() {
	return logisticsName;
    }

    /**
     * Sets the value of the logisticsName property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setLogisticsName(String value) {
	this.logisticsName = value;
    }

    /**
     * Gets the value of the logisticsStatus property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getLogisticsStatus() {
	return logisticsStatus;
    }

    /**
     * Sets the value of the logisticsStatus property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setLogisticsStatus(String value) {
	this.logisticsStatus = value;
    }

    /**
     * Gets the value of the deliverDate property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDeliverDate() {
	return deliverDate;
    }

    /**
     * Sets the value of the deliverDate property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setDeliverDate(String value) {
	this.deliverDate = value;
    }

    /**
     * Gets the value of the failReason property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getFailReason() {
	return failReason;
    }

    /**
     * Sets the value of the failReason property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setFailReason(String value) {
	this.failReason = value;
    }

    /**
     * Gets the value of the ieType property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getIeType() {
	return ieType;
    }

    /**
     * Sets the value of the ieType property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setIeType(String value) {
	this.ieType = value;
    }

}
