//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.06 at 11:32:06 上午 CST 
//

package com.cneport.ecss.exchange.service.cebentity;

import java.math.BigDecimal;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;

/**
 * E贸易运单表头
 * 
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="seqNo">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="36"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="customsCode">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="declareDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="logisticsCode">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="logisticsName">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="200"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="totalLogisticsNo">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="24"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="logisticsNo">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="24"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="trackNo">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="trackStatus">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="orderNo">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="30"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="shipper">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="60"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="shipperAddress">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="shipperTelephone">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="shipperCountry">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="consignee">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="60"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="consigneeAddress">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="consigneeTelephone">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="consigneeCountry">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="idType">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="customerId">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="60"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="crossFreight" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="freight" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="supportValue" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="weight" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="quantity" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="goodsName">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="deliveryWay">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="60"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="shipName">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="destinationPort">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="compareFlag">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ieType">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="stockFlag">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="note">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1000"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="status">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="18"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="applyUser">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="60"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="approveMan">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="60"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="approveTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="approveOpinion">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1024"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="decTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="updateTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ecpCode">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ecpName">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="200"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="indbTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="netWeight" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="packNum" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="wrapType">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="subLogisticsNo">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="24"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="batchNumbers">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="tradeCountry">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="agentCode">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="40"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="agentName">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="billType">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "seqNo", "customsCode", "declareDate",
	"logisticsCode", "logisticsName", "totalLogisticsNo", "logisticsNo",
	"trackNo", "trackStatus", "orderNo", "shipper", "shipperAddress",
	"shipperTelephone", "shipperCountry", "consignee", "consigneeAddress",
	"consigneeTelephone", "consigneeCountry", "idType", "customerId",
	"crossFreight", "freight", "supportValue", "weight", "quantity",
	"goodsName", "deliveryWay", "shipName", "destinationPort",
	"compareFlag", "ieType", "stockFlag", "note", "status", "applyUser",
	"approveMan", "approveTime", "approveOpinion", "decTime", "updateTime",
	"ecpCode", "ecpName", "indbTime", "netWeight", "packNum", "wrapType",
	"subLogisticsNo", "batchNumbers", "tradeCountry", "agentCode",
	"agentName", "billType","modifyMark","trafMode","accessType","voyageNo","billNo",
	"parcelInfo","goodsInfo","appStatus","appUid","appUname","appTime"})
@XmlRootElement(name = "LogisticsInformation")
public class LogisticsInformation {

    @XmlElement(required = true)
    protected String seqNo;
    @XmlElement(required = true)
    protected String customsCode;
    @XmlElement(required = true)
    protected String declareDate;
    @XmlElement(required = true)
    protected String logisticsCode;
    @XmlElement(required = true)
    protected String logisticsName;
    @XmlElement(required = true)
    protected String totalLogisticsNo;
    @XmlElement(required = true)
    protected String logisticsNo;
    @XmlElement(required = true)
    protected String trackNo;
    @XmlElement(required = true)
    protected String trackStatus;
    @XmlElement(required = true)
    protected String orderNo;
    @XmlElement(required = true)
    protected String shipper;
    @XmlElement(required = true)
    protected String shipperAddress;
    @XmlElement(required = true)
    protected String shipperTelephone;
    @XmlElement(required = true)
    protected String shipperCountry;
    @XmlElement(required = true)
    protected String consignee;
    @XmlElement(required = true)
    protected String consigneeAddress;
    @XmlElement(required = true)
    protected String consigneeTelephone;
    @XmlElement(required = true)
    protected String consigneeCountry;
    @XmlElement(required = true)
    protected String idType;
    @XmlElement(required = true)
    protected String customerId;
    @XmlElement(required = true)
    protected BigDecimal crossFreight;
    @XmlElement(required = true)
    protected BigDecimal freight;
    @XmlElement(required = true)
    protected BigDecimal supportValue;
    @XmlElement(required = true)
    protected BigDecimal weight;
    @XmlElement(required = true)
    protected BigDecimal quantity;
    @XmlElement(required = true)
    protected String goodsName;
    @XmlElement(required = true)
    protected String deliveryWay;
    @XmlElement(required = true)
    protected String shipName;
    @XmlElement(required = true)
    protected String destinationPort;
    @XmlElement(required = true)
    protected String compareFlag;
    @XmlElement(required = true)
    protected String ieType;
    @XmlElement(required = true)
    protected String stockFlag;
    @XmlElement(required = true)
    protected String note;
    @XmlElement(required = true)
    protected String status;
    @XmlElement(required = true)
    protected String applyUser;
    @XmlElement(required = true)
    protected String approveMan;
    @XmlElement(required = true)
    protected String approveTime;
    @XmlElement(required = true)
    protected String approveOpinion;
    @XmlElement(required = true)
    protected String decTime;
    @XmlElement(required = true)
    protected String updateTime;
    @XmlElement(required = true)
    protected String ecpCode;
    @XmlElement(required = true)
    protected String ecpName;
    @XmlElement(required = true)
    protected String indbTime;
    @XmlElement(required = true)
    protected BigDecimal netWeight;
    @XmlElement(required = true)
    protected BigDecimal packNum;
    @XmlElement(required = true)
    protected String wrapType;
    @XmlElement(required = true)
    protected String subLogisticsNo;
    @XmlElement(required = true)
    protected String batchNumbers;
    @XmlElement(required = true)
    protected String tradeCountry;
    @XmlElement(required = true)
    protected String agentCode;
    @XmlElement(required = true)
    protected String agentName;
    @XmlElement(required = true)
    protected String billType;
    @XmlElement(required = true)
    protected String modifyMark;
    @XmlTransient
    private String recDetail; // 回执详细信息
    
	@XmlElement(required = true)
	protected String trafMode;
	@XmlElement(required = true)
	protected String accessType;
	@XmlElement(required = true)
	protected String voyageNo;
	@XmlElement(required = true)
	protected String billNo;
	@XmlElement(required = true)
	protected String  parcelInfo;
	@XmlElement(required = true)
	protected String goodsInfo;
	@XmlElement(required = true)
	protected String appTime;
	@XmlElement(required = true)
	protected String appStatus;
	@XmlElement(required = true)
	protected String appUid;
	@XmlElement(required = true)
	protected String appUname;
    
    public String getTrafMode() {
		return trafMode;
	}

	public void setTrafMode(String trafMode) {
		this.trafMode = trafMode;
	}

	public String getAccessType() {
		return accessType;
	}

	public void setAccessType(String accessType) {
		this.accessType = accessType;
	}

	public String getVoyageNo() {
		return voyageNo;
	}

	public void setVoyageNo(String voyageNo) {
		this.voyageNo = voyageNo;
	}

	public String getBillNo() {
		return billNo;
	}

	public void setBillNo(String billNo) {
		this.billNo = billNo;
	}

	public String getParcelInfo() {
		return parcelInfo;
	}

	public void setParcelInfo(String parcelInfo) {
		this.parcelInfo = parcelInfo;
	}

	public String getGoodsInfo() {
		return goodsInfo;
	}

	public void setGoodsInfo(String goodsInfo) {
		this.goodsInfo = goodsInfo;
	}

	public String getAppTime() {
		return appTime;
	}

	public void setAppTime(String appTime) {
		this.appTime = appTime;
	}

	public String getAppStatus() {
		return appStatus;
	}

	public void setAppStatus(String appStatus) {
		this.appStatus = appStatus;
	}

	public String getAppUid() {
		return appUid;
	}

	public void setAppUid(String appUid) {
		this.appUid = appUid;
	}

	public String getAppUname() {
		return appUname;
	}

	public void setAppUname(String appUname) {
		this.appUname = appUname;
	}

	public String getModifyMark() {
		return modifyMark;
	}

	public void setModifyMark(String value) {
		this.modifyMark = value;
	}
    
    /**
     * Gets the value of the seqNo property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSeqNo() {
	return seqNo;
    }

    /**
     * Sets the value of the seqNo property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setSeqNo(String value) {
	this.seqNo = value;
    }

    /**
     * Gets the value of the customsCode property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCustomsCode() {
	return customsCode;
    }

    /**
     * Sets the value of the customsCode property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCustomsCode(String value) {
	this.customsCode = value;
    }

    /**
     * Gets the value of the declareDate property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDeclareDate() {
	return declareDate;
    }

    /**
     * Sets the value of the declareDate property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setDeclareDate(String value) {
	this.declareDate = value;
    }

    /**
     * Gets the value of the logisticsCode property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getLogisticsCode() {
	return logisticsCode;
    }

    /**
     * Sets the value of the logisticsCode property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setLogisticsCode(String value) {
	this.logisticsCode = value;
    }

    /**
     * Gets the value of the logisticsName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getLogisticsName() {
	return logisticsName;
    }

    /**
     * Sets the value of the logisticsName property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setLogisticsName(String value) {
	this.logisticsName = value;
    }

    /**
     * Gets the value of the totalLogisticsNo property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTotalLogisticsNo() {
	return totalLogisticsNo;
    }

    /**
     * Sets the value of the totalLogisticsNo property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setTotalLogisticsNo(String value) {
	this.totalLogisticsNo = value;
    }

    /**
     * Gets the value of the logisticsNo property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getLogisticsNo() {
	return logisticsNo;
    }

    /**
     * Sets the value of the logisticsNo property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setLogisticsNo(String value) {
	this.logisticsNo = value;
    }

    /**
     * Gets the value of the trackNo property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTrackNo() {
	return trackNo;
    }

    /**
     * Sets the value of the trackNo property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setTrackNo(String value) {
	this.trackNo = value;
    }

    /**
     * Gets the value of the trackStatus property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTrackStatus() {
	return trackStatus;
    }

    /**
     * Sets the value of the trackStatus property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setTrackStatus(String value) {
	this.trackStatus = value;
    }

    /**
     * Gets the value of the orderNo property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getOrderNo() {
	return orderNo;
    }

    /**
     * Sets the value of the orderNo property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setOrderNo(String value) {
	this.orderNo = value;
    }

    /**
     * Gets the value of the shipper property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getShipper() {
	return shipper;
    }

    /**
     * Sets the value of the shipper property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setShipper(String value) {
	this.shipper = value;
    }

    /**
     * Gets the value of the shipperAddress property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getShipperAddress() {
	return shipperAddress;
    }

    /**
     * Sets the value of the shipperAddress property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setShipperAddress(String value) {
	this.shipperAddress = value;
    }

    /**
     * Gets the value of the shipperTelephone property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getShipperTelephone() {
	return shipperTelephone;
    }

    /**
     * Sets the value of the shipperTelephone property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setShipperTelephone(String value) {
	this.shipperTelephone = value;
    }

    /**
     * Gets the value of the shipperCountry property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getShipperCountry() {
	return shipperCountry;
    }

    /**
     * Sets the value of the shipperCountry property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setShipperCountry(String value) {
	this.shipperCountry = value;
    }

    /**
     * Gets the value of the consignee property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getConsignee() {
	return consignee;
    }

    /**
     * Sets the value of the consignee property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setConsignee(String value) {
	this.consignee = value;
    }

    /**
     * Gets the value of the consigneeAddress property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getConsigneeAddress() {
	return consigneeAddress;
    }

    /**
     * Sets the value of the consigneeAddress property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setConsigneeAddress(String value) {
	this.consigneeAddress = value;
    }

    /**
     * Gets the value of the consigneeTelephone property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getConsigneeTelephone() {
	return consigneeTelephone;
    }

    /**
     * Sets the value of the consigneeTelephone property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setConsigneeTelephone(String value) {
	this.consigneeTelephone = value;
    }

    /**
     * Gets the value of the consigneeCountry property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getConsigneeCountry() {
	return consigneeCountry;
    }

    /**
     * Sets the value of the consigneeCountry property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setConsigneeCountry(String value) {
	this.consigneeCountry = value;
    }

    /**
     * Gets the value of the idType property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getIdType() {
	return idType;
    }

    /**
     * Sets the value of the idType property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setIdType(String value) {
	this.idType = value;
    }

    /**
     * Gets the value of the customerId property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCustomerId() {
	return customerId;
    }

    /**
     * Sets the value of the customerId property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCustomerId(String value) {
	this.customerId = value;
    }

    /**
     * Gets the value of the crossFreight property.
     * 
     * @return possible object is {@link BigDecimal }
     * 
     */
    public BigDecimal getCrossFreight() {
	return crossFreight;
    }

    /**
     * Sets the value of the crossFreight property.
     * 
     * @param value
     *            allowed object is {@link BigDecimal }
     * 
     */
    public void setCrossFreight(BigDecimal value) {
	this.crossFreight = value;
    }

    /**
     * Gets the value of the freight property.
     * 
     * @return possible object is {@link BigDecimal }
     * 
     */
    public BigDecimal getFreight() {
	return freight;
    }

    /**
     * Sets the value of the freight property.
     * 
     * @param value
     *            allowed object is {@link BigDecimal }
     * 
     */
    public void setFreight(BigDecimal value) {
	this.freight = value;
    }

    /**
     * Gets the value of the supportValue property.
     * 
     * @return possible object is {@link BigDecimal }
     * 
     */
    public BigDecimal getSupportValue() {
	return supportValue;
    }

    /**
     * Sets the value of the supportValue property.
     * 
     * @param value
     *            allowed object is {@link BigDecimal }
     * 
     */
    public void setSupportValue(BigDecimal value) {
	this.supportValue = value;
    }

    /**
     * Gets the value of the weight property.
     * 
     * @return possible object is {@link BigDecimal }
     * 
     */
    public BigDecimal getWeight() {
	return weight;
    }

    /**
     * Sets the value of the weight property.
     * 
     * @param value
     *            allowed object is {@link BigDecimal }
     * 
     */
    public void setWeight(BigDecimal value) {
	this.weight = value;
    }

    /**
     * Gets the value of the quantity property.
     * 
     * @return possible object is {@link BigDecimal }
     * 
     */
    public BigDecimal getQuantity() {
	return quantity;
    }

    /**
     * Sets the value of the quantity property.
     * 
     * @param value
     *            allowed object is {@link BigDecimal }
     * 
     */
    public void setQuantity(BigDecimal value) {
	this.quantity = value;
    }

    /**
     * Gets the value of the goodsName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getGoodsName() {
	return goodsName;
    }

    /**
     * Sets the value of the goodsName property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setGoodsName(String value) {
	this.goodsName = value;
    }

    /**
     * Gets the value of the deliveryWay property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDeliveryWay() {
	return deliveryWay;
    }

    /**
     * Sets the value of the deliveryWay property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setDeliveryWay(String value) {
	this.deliveryWay = value;
    }

    /**
     * Gets the value of the shipName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getShipName() {
	return shipName;
    }

    /**
     * Sets the value of the shipName property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setShipName(String value) {
	this.shipName = value;
    }

    /**
     * Gets the value of the destinationPort property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDestinationPort() {
	return destinationPort;
    }

    /**
     * Sets the value of the destinationPort property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setDestinationPort(String value) {
	this.destinationPort = value;
    }

    /**
     * Gets the value of the compareFlag property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCompareFlag() {
	return compareFlag;
    }

    /**
     * Sets the value of the compareFlag property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCompareFlag(String value) {
	this.compareFlag = value;
    }

    /**
     * Gets the value of the ieType property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getIeType() {
	return ieType;
    }

    /**
     * Sets the value of the ieType property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setIeType(String value) {
	this.ieType = value;
    }

    /**
     * Gets the value of the stockFlag property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getStockFlag() {
	return stockFlag;
    }

    /**
     * Sets the value of the stockFlag property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setStockFlag(String value) {
	this.stockFlag = value;
    }

    /**
     * Gets the value of the note property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getNote() {
	return note;
    }

    /**
     * Sets the value of the note property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setNote(String value) {
	this.note = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getStatus() {
	return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setStatus(String value) {
	this.status = value;
    }

    /**
     * Gets the value of the applyUser property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getApplyUser() {
	return applyUser;
    }

    /**
     * Sets the value of the applyUser property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setApplyUser(String value) {
	this.applyUser = value;
    }

    /**
     * Gets the value of the approveMan property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getApproveMan() {
	return approveMan;
    }

    /**
     * Sets the value of the approveMan property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setApproveMan(String value) {
	this.approveMan = value;
    }

    /**
     * Gets the value of the approveTime property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getApproveTime() {
	return approveTime;
    }

    /**
     * Sets the value of the approveTime property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setApproveTime(String value) {
	this.approveTime = value;
    }

    /**
     * Gets the value of the approveOpinion property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getApproveOpinion() {
	return approveOpinion;
    }

    /**
     * Sets the value of the approveOpinion property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setApproveOpinion(String value) {
	this.approveOpinion = value;
    }

    /**
     * Gets the value of the decTime property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDecTime() {
	return decTime;
    }

    /**
     * Sets the value of the decTime property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setDecTime(String value) {
	this.decTime = value;
    }

    /**
     * Gets the value of the updateTime property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getUpdateTime() {
	return updateTime;
    }

    /**
     * Sets the value of the updateTime property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setUpdateTime(String value) {
	this.updateTime = value;
    }

    /**
     * Gets the value of the ecpCode property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getEcpCode() {
	return ecpCode;
    }

    /**
     * Sets the value of the ecpCode property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setEcpCode(String value) {
	this.ecpCode = value;
    }

    /**
     * Gets the value of the ecpName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getEcpName() {
	return ecpName;
    }

    /**
     * Sets the value of the ecpName property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setEcpName(String value) {
	this.ecpName = value;
    }

    /**
     * Gets the value of the indbTime property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getIndbTime() {
	return indbTime;
    }

    /**
     * Sets the value of the indbTime property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setIndbTime(String value) {
	this.indbTime = value;
    }

    /**
     * Gets the value of the netWeight property.
     * 
     * @return possible object is {@link BigDecimal }
     * 
     */
    public BigDecimal getNetWeight() {
	return netWeight;
    }

    /**
     * Sets the value of the netWeight property.
     * 
     * @param value
     *            allowed object is {@link BigDecimal }
     * 
     */
    public void setNetWeight(BigDecimal value) {
	this.netWeight = value;
    }

    /**
     * Gets the value of the packNum property.
     * 
     * @return possible object is {@link BigDecimal }
     * 
     */
    public BigDecimal getPackNum() {
	return packNum;
    }

    /**
     * Sets the value of the packNum property.
     * 
     * @param value
     *            allowed object is {@link BigDecimal }
     * 
     */
    public void setPackNum(BigDecimal value) {
	this.packNum = value;
    }

    /**
     * Gets the value of the wrapType property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getWrapType() {
	return wrapType;
    }

    /**
     * Sets the value of the wrapType property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setWrapType(String value) {
	this.wrapType = value;
    }

    /**
     * Gets the value of the subLogisticsNo property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSubLogisticsNo() {
	return subLogisticsNo;
    }

    /**
     * Sets the value of the subLogisticsNo property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setSubLogisticsNo(String value) {
	this.subLogisticsNo = value;
    }

    /**
     * Gets the value of the batchNumbers property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getBatchNumbers() {
	return batchNumbers;
    }

    /**
     * Sets the value of the batchNumbers property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setBatchNumbers(String value) {
	this.batchNumbers = value;
    }

    /**
     * Gets the value of the tradeCountry property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTradeCountry() {
	return tradeCountry;
    }

    /**
     * Sets the value of the tradeCountry property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setTradeCountry(String value) {
	this.tradeCountry = value;
    }

    /**
     * Gets the value of the agentCode property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getAgentCode() {
	return agentCode;
    }

    /**
     * Sets the value of the agentCode property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setAgentCode(String value) {
	this.agentCode = value;
    }

    /**
     * Gets the value of the agentName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getAgentName() {
	return agentName;
    }

    /**
     * Sets the value of the agentName property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setAgentName(String value) {
	this.agentName = value;
    }

    /**
     * Gets the value of the billType property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getBillType() {
	return billType;
    }

    /**
     * Sets the value of the billType property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setBillType(String value) {
	this.billType = value;
    }

    public String getRecDetail() {
	return recDetail;
    }

    public void setRecDetail(String recDetail) {
	this.recDetail = recDetail;
    }

}
