//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.08 at 10:37:45 ���� CST 
//

package com.cneport.ecss.exchange.service.entity;

import java.math.BigDecimal;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * ��Ʒ��������
 * 
 * <p>
 * Java class for GoodsList complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="GoodsList">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="seqNo">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="36"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="listNo">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="18"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="goodsNo">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="shelfGoodsName">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="250"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="superviseId">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="30"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="describe">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="250"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="codeTs">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="goodsName">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="250"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="goodsModel">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="250"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="unit">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="currency">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="price">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="19"/>
 *               &lt;fractionDigits value="5"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="priceRmb">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="19"/>
 *               &lt;fractionDigits value="5"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="taxCode">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="8"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ecpCode">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="40"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ecpName">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="country">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="image">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="250"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="barCode">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="40"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="itemNo">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="isTax">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="applyUser">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="60"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="status">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="18"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="approveMan">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="60"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="approveTime">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="approveOption">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1024"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="decTime">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="updateTime">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="modifyTimes">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="9"/>
 *               &lt;fractionDigits value="0"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="isPermit">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="limitationGoodsCode">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="positionSeq">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="indbTime">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="brands">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="unit1">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="unit2">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="shelfGoodsNameForeign">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="250"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="approveType">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GoodsList", propOrder = { "seqNo", "listNo", "goodsNo",
	"shelfGoodsName", "superviseId", "describe", "codeTs", "goodsName",
	"goodsModel", "unit", "currency", "price", "priceRmb", "taxCode",
	"ecpCode", "ecpName", "country", "image", "barCode", "itemNo", "isTax",
	"applyUser", "status", "approveMan", "approveTime", "approveOption",
	"decTime", "updateTime", "modifyTimes", "isPermit",
	"limitationGoodsCode", "positionSeq", "indbTime", "brands", "unit1",
	"unit2", "shelfGoodsNameForeign", "approveType", "batchNumbers" })
public class GoodsList {

    @XmlElement(required = true)
    protected String seqNo;
    @XmlElement(required = true)
    protected String listNo;
    @XmlElement(required = true)
    protected String goodsNo;
    @XmlElement(required = true)
    protected String shelfGoodsName;
    @XmlElement(required = true)
    protected String superviseId;
    @XmlElement(required = true)
    protected String describe;
    @XmlElement(required = true)
    protected String codeTs;
    @XmlElement(required = true)
    protected String goodsName;
    @XmlElement(required = true)
    protected String goodsModel;
    @XmlElement(required = true)
    protected String unit;
    @XmlElement(required = true)
    protected String currency;
    @XmlElement(required = true)
    protected BigDecimal price;
    @XmlElement(required = true)
    protected BigDecimal priceRmb;
    @XmlElement(required = true)
    protected String taxCode;
    @XmlElement(required = true)
    protected String ecpCode;
    @XmlElement(required = true)
    protected String ecpName;
    @XmlElement(required = true)
    protected String country;
    @XmlElement(required = true)
    protected String image;
    @XmlElement(required = true)
    protected String barCode;
    @XmlElement(required = true)
    protected String itemNo;
    @XmlElement(required = true)
    protected String isTax;
    @XmlElement(required = true)
    protected String applyUser;
    @XmlElement(required = true)
    protected String status;
    @XmlElement(required = true)
    protected String approveMan;
    @XmlElement(required = true)
    protected String approveTime;
    @XmlElement(required = true)
    protected String approveOption;
    @XmlElement(required = true)
    protected String decTime;
    @XmlElement(required = true)
    protected String updateTime;
    @XmlElement(required = true)
    protected BigDecimal modifyTimes;
    @XmlElement(required = true)
    protected String isPermit;
    @XmlElement(required = true)
    protected String limitationGoodsCode;
    @XmlElement(required = true)
    protected String positionSeq;
    @XmlElement(required = true)
    protected String indbTime;
    @XmlElement(required = true)
    protected String brands;
    @XmlElement(required = true)
    protected String unit1;
    @XmlElement(required = true)
    protected String unit2;
    @XmlElement(required = true)
    protected String shelfGoodsNameForeign;
    @XmlElement(required = true)
    protected String approveType;
    @XmlElement(required = true)
    protected String batchNumbers;

    /**
     * Gets the value of the seqNo property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSeqNo() {
	return seqNo;
    }

    /**
     * Sets the value of the seqNo property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setSeqNo(String value) {
	this.seqNo = value;
    }

    /**
     * Gets the value of the listNo property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getListNo() {
	return listNo;
    }

    /**
     * Sets the value of the listNo property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setListNo(String value) {
	this.listNo = value;
    }

    /**
     * Gets the value of the goodsNo property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getGoodsNo() {
	return goodsNo;
    }

    /**
     * Sets the value of the goodsNo property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setGoodsNo(String value) {
	this.goodsNo = value;
    }

    /**
     * Gets the value of the shelfGoodsName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getShelfGoodsName() {
	return shelfGoodsName;
    }

    /**
     * Sets the value of the shelfGoodsName property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setShelfGoodsName(String value) {
	this.shelfGoodsName = value;
    }

    /**
     * Gets the value of the superviseId property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSuperviseId() {
	return superviseId;
    }

    /**
     * Sets the value of the superviseId property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setSuperviseId(String value) {
	this.superviseId = value;
    }

    /**
     * Gets the value of the describe property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDescribe() {
	return describe;
    }

    /**
     * Sets the value of the describe property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setDescribe(String value) {
	this.describe = value;
    }

    /**
     * Gets the value of the codeTs property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCodeTs() {
	return codeTs;
    }

    /**
     * Sets the value of the codeTs property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCodeTs(String value) {
	this.codeTs = value;
    }

    /**
     * Gets the value of the goodsName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getGoodsName() {
	return goodsName;
    }

    /**
     * Sets the value of the goodsName property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setGoodsName(String value) {
	this.goodsName = value;
    }

    /**
     * Gets the value of the goodsModel property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getGoodsModel() {
	return goodsModel;
    }

    /**
     * Sets the value of the goodsModel property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setGoodsModel(String value) {
	this.goodsModel = value;
    }

    /**
     * Gets the value of the unit property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getUnit() {
	return unit;
    }

    /**
     * Sets the value of the unit property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setUnit(String value) {
	this.unit = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCurrency() {
	return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCurrency(String value) {
	this.currency = value;
    }

    /**
     * Gets the value of the price property.
     * 
     * @return possible object is {@link BigDecimal }
     * 
     */
    public BigDecimal getPrice() {
	return price;
    }

    /**
     * Sets the value of the price property.
     * 
     * @param value
     *            allowed object is {@link BigDecimal }
     * 
     */
    public void setPrice(BigDecimal value) {
	this.price = value;
    }

    /**
     * Gets the value of the priceRmb property.
     * 
     * @return possible object is {@link BigDecimal }
     * 
     */
    public BigDecimal getPriceRmb() {
	return priceRmb;
    }

    /**
     * Sets the value of the priceRmb property.
     * 
     * @param value
     *            allowed object is {@link BigDecimal }
     * 
     */
    public void setPriceRmb(BigDecimal value) {
	this.priceRmb = value;
    }

    /**
     * Gets the value of the taxCode property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTaxCode() {
	return taxCode;
    }

    /**
     * Sets the value of the taxCode property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setTaxCode(String value) {
	this.taxCode = value;
    }

    /**
     * Gets the value of the ecpCode property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getEcpCode() {
	return ecpCode;
    }

    /**
     * Sets the value of the ecpCode property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setEcpCode(String value) {
	this.ecpCode = value;
    }

    /**
     * Gets the value of the ecpName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getEcpName() {
	return ecpName;
    }

    /**
     * Sets the value of the ecpName property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setEcpName(String value) {
	this.ecpName = value;
    }

    /**
     * Gets the value of the country property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCountry() {
	return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCountry(String value) {
	this.country = value;
    }

    /**
     * Gets the value of the image property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getImage() {
	return image;
    }

    /**
     * Sets the value of the image property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setImage(String value) {
	this.image = value;
    }

    /**
     * Gets the value of the barCode property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getBarCode() {
	return barCode;
    }

    /**
     * Sets the value of the barCode property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setBarCode(String value) {
	this.barCode = value;
    }

    /**
     * Gets the value of the itemNo property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getItemNo() {
	return itemNo;
    }

    /**
     * Sets the value of the itemNo property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setItemNo(String value) {
	this.itemNo = value;
    }

    /**
     * Gets the value of the isTax property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getIsTax() {
	return isTax;
    }

    /**
     * Sets the value of the isTax property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setIsTax(String value) {
	this.isTax = value;
    }

    /**
     * Gets the value of the applyUser property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getApplyUser() {
	return applyUser;
    }

    /**
     * Sets the value of the applyUser property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setApplyUser(String value) {
	this.applyUser = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getStatus() {
	return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setStatus(String value) {
	this.status = value;
    }

    /**
     * Gets the value of the approveMan property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getApproveMan() {
	return approveMan;
    }

    /**
     * Sets the value of the approveMan property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setApproveMan(String value) {
	this.approveMan = value;
    }

    /**
     * Gets the value of the approveTime property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getApproveTime() {
	return approveTime;
    }

    /**
     * Sets the value of the approveTime property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setApproveTime(String value) {
	this.approveTime = value;
    }

    /**
     * Gets the value of the approveOption property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getApproveOption() {
	return approveOption;
    }

    /**
     * Sets the value of the approveOption property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setApproveOption(String value) {
	this.approveOption = value;
    }

    /**
     * Gets the value of the decTime property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDecTime() {
	return decTime;
    }

    /**
     * Sets the value of the decTime property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setDecTime(String value) {
	this.decTime = value;
    }

    /**
     * Gets the value of the updateTime property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getUpdateTime() {
	return updateTime;
    }

    /**
     * Sets the value of the updateTime property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setUpdateTime(String value) {
	this.updateTime = value;
    }

    /**
     * Gets the value of the modifyTimes property.
     * 
     * @return possible object is {@link BigDecimal }
     * 
     */
    public BigDecimal getModifyTimes() {
	return modifyTimes;
    }

    /**
     * Sets the value of the modifyTimes property.
     * 
     * @param value
     *            allowed object is {@link BigDecimal }
     * 
     */
    public void setModifyTimes(BigDecimal value) {
	this.modifyTimes = value;
    }

    /**
     * Gets the value of the isPermit property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getIsPermit() {
	return isPermit;
    }

    /**
     * Sets the value of the isPermit property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setIsPermit(String value) {
	this.isPermit = value;
    }

    /**
     * Gets the value of the limitationGoodsCode property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getLimitationGoodsCode() {
	return limitationGoodsCode;
    }

    /**
     * Sets the value of the limitationGoodsCode property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setLimitationGoodsCode(String value) {
	this.limitationGoodsCode = value;
    }

    /**
     * Gets the value of the positionSeq property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getPositionSeq() {
	return positionSeq;
    }

    /**
     * Sets the value of the positionSeq property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setPositionSeq(String value) {
	this.positionSeq = value;
    }

    /**
     * Gets the value of the indbTime property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getIndbTime() {
	return indbTime;
    }

    /**
     * Sets the value of the indbTime property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setIndbTime(String value) {
	this.indbTime = value;
    }

    /**
     * Gets the value of the brands property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getBrands() {
	return brands;
    }

    /**
     * Sets the value of the brands property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setBrands(String value) {
	this.brands = value;
    }

    /**
     * Gets the value of the unit1 property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getUnit1() {
	return unit1;
    }

    /**
     * Sets the value of the unit1 property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setUnit1(String value) {
	this.unit1 = value;
    }

    /**
     * Gets the value of the unit2 property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getUnit2() {
	return unit2;
    }

    /**
     * Sets the value of the unit2 property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setUnit2(String value) {
	this.unit2 = value;
    }

    /**
     * Gets the value of the shelfGoodsNameForeign property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getShelfGoodsNameForeign() {
	return shelfGoodsNameForeign;
    }

    /**
     * Sets the value of the shelfGoodsNameForeign property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setShelfGoodsNameForeign(String value) {
	this.shelfGoodsNameForeign = value;
    }

    /**
     * Gets the value of the approveType property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getApproveType() {
	return approveType;
    }

    /**
     * Sets the value of the approveType property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setApproveType(String value) {
	this.approveType = value;
    }

    public String getBatchNumbers() {
	return batchNumbers;
    }

    /**
     * Sets the value of the approveType property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setBatchNumbers(String value) {
	this.batchNumbers = value;
    }

}
