//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.22 at 05:04:32 ���� CST 
//


package com.cneport.ecss.exchange.service.entity;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="GoodsHead" type="{}GoodsHead"/>
 *         &lt;element name="GoodsList" type="{}GoodsList" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "goodsHead",
    "goodsList"
})
@XmlRootElement(name = "Goods")
public class Goods {

    public void setGoodsList(List<GoodsList> goodsList) {
		this.goodsList = goodsList;
	}

	@XmlElement(name = "GoodsHead", required = true)
    protected GoodsHead goodsHead;
    @XmlElement(name = "GoodsList", required = true)
    protected List<GoodsList> goodsList;

    /**
     * Gets the value of the goodsHead property.
     * 
     * @return
     *     possible object is
     *     {@link GoodsHead }
     *     
     */
    public GoodsHead getGoodsHead() {
        return goodsHead;
    }

    /**
     * Sets the value of the goodsHead property.
     * 
     * @param value
     *     allowed object is
     *     {@link GoodsHead }
     *     
     */
    public void setGoodsHead(GoodsHead value) {
        this.goodsHead = value;
    }

    /**
     * Gets the value of the goodsList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the goodsList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGoodsList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GoodsList }
     * 
     * 
     */
    public List<GoodsList> getGoodsList() {
        if (goodsList == null) {
            goodsList = new ArrayList<GoodsList>();
        }
        return this.goodsList;
    }

}
