//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.22 at 02:59:37 下午 CST 
//

package com.cneport.ecss.exchange.service.entity;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}LogisticsInformation"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "logisticsInformation" })
@XmlRootElement(name = "LogisticsReponse")
public class LogisticsReponse {

    @XmlElement(name = "LogisticsInformation", required = true)
    protected LogisticsInformation logisticsInformation;

    /**
     * Gets the value of the logisticsInformation property.
     * 
     * @return possible object is {@link LogisticsInformation }
     * 
     */
    public LogisticsInformation getLogisticsInformation() {
	return logisticsInformation;
    }

    /**
     * Sets the value of the logisticsInformation property.
     * 
     * @param value
     *            allowed object is {@link LogisticsInformation }
     * 
     */
    public void setLogisticsInformation(LogisticsInformation value) {
	this.logisticsInformation = value;
    }

}
