//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.10 at 03:46:05 下午 CST 
//

package com.cneport.ecss.exchange.service.entity;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * E贸易运单表头
 * 
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="LogisticsCode">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="LogisticsName">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="200"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="TotalLogisticsNo">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="24"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="LogisticsNo">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="24"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="status">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="detail">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1000"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "logisticsCode", "logisticsName",
	"totalLogisticsNo", "logisticsNo", "status", "detail" })
@XmlRootElement(name = "LogisticsInformationRec")
public class LogisticsInformationRec {

    @XmlElement(name = "LogisticsCode", required = true)
    protected String logisticsCode;
    @XmlElement(name = "LogisticsName", required = true)
    protected String logisticsName;
    @XmlElement(name = "TotalLogisticsNo", required = true)
    protected String totalLogisticsNo;
    @XmlElement(name = "LogisticsNo", required = true)
    protected String logisticsNo;
    @XmlElement(required = true)
    protected String status;
    @XmlElement(required = true)
    protected String detail;

    /**
     * Gets the value of the logisticsCode property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getLogisticsCode() {
	return logisticsCode;
    }

    /**
     * Sets the value of the logisticsCode property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setLogisticsCode(String value) {
	this.logisticsCode = value;
    }

    /**
     * Gets the value of the logisticsName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getLogisticsName() {
	return logisticsName;
    }

    /**
     * Sets the value of the logisticsName property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setLogisticsName(String value) {
	this.logisticsName = value;
    }

    /**
     * Gets the value of the totalLogisticsNo property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTotalLogisticsNo() {
	return totalLogisticsNo;
    }

    /**
     * Sets the value of the totalLogisticsNo property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setTotalLogisticsNo(String value) {
	this.totalLogisticsNo = value;
    }

    /**
     * Gets the value of the logisticsNo property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getLogisticsNo() {
	return logisticsNo;
    }

    /**
     * Sets the value of the logisticsNo property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setLogisticsNo(String value) {
	this.logisticsNo = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getStatus() {
	return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setStatus(String value) {
	this.status = value;
    }

    /**
     * Gets the value of the detail property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDetail() {
	return detail;
    }

    /**
     * Sets the value of the detail property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setDetail(String value) {
	this.detail = value;
    }

}
