//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.14 at 10:42:45 AM CST 
//

package com.cneport.ecss.exchange.service.entity;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the com.cneport.ecss.exchange.service.entity
 * package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    /**
     * Create a new ObjectFactory that can be used to create new instances of
     * schema derived classes for package:
     * com.cneport.ecss.exchange.service.entity
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PersonalDeclareHead }
     * 
     */
    public PersonalDeclareHead createPersonalDeclareHead() {
	return new PersonalDeclareHead();
    }

    /**
     * Create an instance of {@link OrderPaymentLogistics }
     * 
     */
    public OrderPaymentLogistics createOrderPaymentLogistics() {
	return new OrderPaymentLogistics();
    }

    /**
     * Create an instance of {@link PersonalDeclare }
     * 
     */
    public PersonalDeclare createPersonalDeclare() {
	return new PersonalDeclare();
    }

    /**
     * Create an instance of {@link LogisticsInformation }
     * 
     */
    public LogisticsInformation createLogisticsInformation() {
	return new LogisticsInformation();
    }

    /**
     * Create an instance of {@link PaymentInformation }
     * 
     */
    public PaymentInformation createPaymentInformation() {
	return new PaymentInformation();
    }

    /**
     * Create an instance of {@link OrderHead }
     * 
     */
    public OrderHead createOrderHead() {
	return new OrderHead();
    }

    /**
     * Create an instance of {@link Order }
     * 
     */
    public Order createOrder() {
	return new Order();
    }

    /**
     * Create an instance of {@link PaymentResponse }
     * 
     */
    public PaymentResponse createPaymentResponse() {
	return new PaymentResponse();
    }

    /**
     * Create an instance of {@link PersonalDeclareResponse }
     * 
     */
    public PersonalDeclareResponse createPersonalDeclareResponse() {
	return new PersonalDeclareResponse();
    }

    /**
     * Create an instance of {@link OrderReponse }
     * 
     */
    public OrderReponse createOrderReponse() {
	return new OrderReponse();
    }

    /**
     * Create an instance of {@link PersonalDeclareList }
     * 
     */
    public PersonalDeclareList createPersonalDeclareList() {
	return new PersonalDeclareList();
    }

    /**
     * Create an instance of {@link PersonalDeclareRequest }
     * 
     */
    public PersonalDeclareRequest createPersonalDeclareRequest() {
	return new PersonalDeclareRequest();
    }

    /**
     * Create an instance of {@link LogisticsReponse }
     * 
     */
    public LogisticsReponse createLogisticsReponse() {
	return new LogisticsReponse();
    }

    /**
     * Create an instance of {@link OrderList }
     * 
     */
    public OrderList createOrderList() {
	return new OrderList();
    }

    public Goods createGoods() {
	return new Goods();
    }

    public GoodsHead createGoodsHead() {
	return new GoodsHead();
    }

    public GoodsList createGoodsList() {
	return new GoodsList();
    }

    /**
     * Create an instance of {@link LogisticsStatus }
     * 
     */
    public LogisticsStatus createLogisticsStatus() {
	return new LogisticsStatus();
    }

}
