//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.22 at 02:59:37 下午 CST 
//

package com.cneport.ecss.exchange.service.entity;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="OrderHead" type="{}OrderHead"/>
 *         &lt;element name="OrderList" type="{}OrderList" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="OrderPaymentLogistics" type="{}OrderPaymentLogistics"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "orderHead", "orderList",
	"orderPaymentLogistics" })
@XmlRootElement(name = "Order")
public class Order {

    @XmlElement(name = "OrderHead", required = true)
    protected OrderHead orderHead;
    @XmlElement(name = "OrderList")
    protected List<OrderList> orderList;
    @XmlElement(name = "OrderPaymentLogistics", required = true)
    protected OrderPaymentLogistics orderPaymentLogistics;

    @XmlTransient
    private LogisticsInformation logisticsInformation; // 运单表头
    @XmlTransient
    private PaymentInformation paymentInformation; // 支付信息

    /**
     * Gets the value of the orderHead property.
     * 
     * @return possible object is {@link OrderHead }
     * 
     */
    public OrderHead getOrderHead() {
	return orderHead;
    }

    /**
     * Sets the value of the orderHead property.
     * 
     * @param value
     *            allowed object is {@link OrderHead }
     * 
     */
    public void setOrderHead(OrderHead value) {
	this.orderHead = value;
    }

    /**
     * Gets the value of the orderList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the orderList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getOrderList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OrderList }
     * 
     * 
     */
    public List<OrderList> getOrderList() {
	if (orderList == null) {
	    orderList = new ArrayList<OrderList>();
	}
	return this.orderList;
    }

    /**
     * Gets the value of the orderPaymentLogistics property.
     * 
     * @return possible object is {@link OrderPaymentLogistics }
     * 
     */
    public OrderPaymentLogistics getOrderPaymentLogistics() {
	return orderPaymentLogistics;
    }

    /**
     * Sets the value of the orderPaymentLogistics property.
     * 
     * @param value
     *            allowed object is {@link OrderPaymentLogistics }
     * 
     */
    public void setOrderPaymentLogistics(OrderPaymentLogistics value) {
	this.orderPaymentLogistics = value;
    }

    public void setOrderList(List<OrderList> orderList) {
	this.orderList = orderList;
    }

    public LogisticsInformation getLogisticsInformation() {
	return logisticsInformation;
    }

    public void setLogisticsInformation(
	    LogisticsInformation logisticsInformation) {
	this.logisticsInformation = logisticsInformation;
    }

    public PaymentInformation getPaymentInformation() {
	return paymentInformation;
    }

    public void setPaymentInformation(PaymentInformation paymentInformation) {
	this.paymentInformation = paymentInformation;
    }

}
