//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.22 at 02:59:37 下午 CST 
//

package com.cneport.ecss.exchange.service.entity;

import java.math.BigDecimal;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;

/**
 * 订单表头
 * 
 * <p>
 * Java class for OrderHead complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="OrderHead">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="seqNo">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="36"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="customsCode">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="cbeCode">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="cbeName">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="200"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ecpCode">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ecpName">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="200"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="customer">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="60"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="idType">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="customerId">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="60"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="orderNo">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="30"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="charge">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="goodsValue">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="freight">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="other">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="tax" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="shipper">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="60"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="shipperAddress">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="shipperTelephone">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="shipperCountry">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="consignee">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="60"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="consigneeAddress">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="consigneeTelephone">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="consigneeCountry">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ieType">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="compareFlag">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="note">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1000"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="declareDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="applyUser">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="60"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="status">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="18"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="approveMan">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="60"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="approveTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="approveOpinion">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1024"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="updateTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="buildStatus">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="indbTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="currency">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="batchNumbers">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="totalLogisticsNo">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="24"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="tradeCountry">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="agentCode">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="40"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="agentName">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OrderHead", propOrder = { "seqNo", "customsCode", "cbeCode",
	"cbeName", "ecpCode", "ecpName", "customer", "idType", "customerId",
	"orderNo", "charge", "goodsValue", "freight", "other", "tax",
	"shipper", "shipperAddress", "shipperTelephone", "shipperCountry",
	"consignee", "consigneeAddress", "consigneeTelephone",
	"consigneeCountry", "ieType", "compareFlag", "note", "declareDate",
	"applyUser", "status", "approveMan", "approveTime", "approveOpinion",
	"updateTime", "buildStatus", "indbTime", "currency", "batchNumbers",
	"totalLogisticsNo", "tradeCountry", "agentCode", "agentName","modifyMark"  })
public class OrderHead {

    @XmlElement(required = true)
    protected String seqNo;
    @XmlElement(required = true)
    protected String customsCode;
    @XmlElement(required = true)
    protected String cbeCode;
    @XmlElement(required = true)
    protected String cbeName;
    @XmlElement(required = true)
    protected String ecpCode;
    @XmlElement(required = true)
    protected String ecpName;
    @XmlElement(required = true)
    protected String customer;
    @XmlElement(required = true)
    protected String idType;
    @XmlElement(required = true)
    protected String customerId;
    @XmlElement(required = true)
    protected String orderNo;
    @XmlElement(required = true)
    protected BigDecimal charge;
    @XmlElement(required = true)
    protected BigDecimal goodsValue;
    @XmlElement(required = true)
    protected BigDecimal freight;
    @XmlElement(required = true)
    protected BigDecimal other;
    @XmlElement(required = true)
    protected BigDecimal tax;
    @XmlElement(required = true)
    protected String shipper;
    @XmlElement(required = true)
    protected String shipperAddress;
    @XmlElement(required = true)
    protected String shipperTelephone;
    @XmlElement(required = true)
    protected String shipperCountry;
    @XmlElement(required = true)
    protected String consignee;
    @XmlElement(required = true)
    protected String consigneeAddress;
    @XmlElement(required = true)
    protected String consigneeTelephone;
    @XmlElement(required = true)
    protected String consigneeCountry;
    @XmlElement(required = true)
    protected String ieType;
    @XmlElement(required = true)
    protected String compareFlag;
    @XmlElement(required = true)
    protected String note;
    @XmlElement(required = true)
    protected String declareDate;
    @XmlElement(required = true)
    protected String applyUser;
    @XmlElement(required = true)
    protected String status;
    @XmlElement(required = true)
    protected String approveMan;
    @XmlElement(required = true)
    protected String approveTime;
    @XmlElement(required = true)
    protected String approveOpinion;
    @XmlElement(required = true)
    protected String updateTime;
    @XmlElement(required = true)
    protected String buildStatus;
    @XmlElement(required = true)
    protected String indbTime;
    @XmlElement(required = true)
    protected String currency;
    @XmlElement(required = true)
    protected String batchNumbers;
    @XmlElement(required = true)
    protected String totalLogisticsNo;
    @XmlElement(required = true)
    protected String tradeCountry;
    @XmlElement(required = true)
    protected String agentCode;
    @XmlElement(required = true)
    protected String agentName;
    @XmlElement(required = true)
    protected String modifyMark;
    
    
    @XmlTransient
    private String paymentCode; // 支付企业代码
    @XmlTransient
    private String paymentName; // 支付企业名称
    @XmlTransient
    private String paymentNo; // 支付交易号
    @XmlTransient
    private String logisticsCode; // 物流企业代码
    @XmlTransient
    private String logisticsName; // 物流企业名称
    @XmlTransient
    private String logisticsNo; // 物流运单号

    @XmlTransient
    private String recDetail; // 回执详细信息

    
   

    public String getModifyMark() {
		return modifyMark;
	}

	public void setModifyMark(String value) {
		this.modifyMark = value;
	}
    /**
     * Gets the value of the seqNo property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSeqNo() {
	return seqNo;
    }

    /**
     * Sets the value of the seqNo property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setSeqNo(String value) {
	this.seqNo = value;
    }

    /**
     * Gets the value of the customsCode property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCustomsCode() {
	return customsCode;
    }

    /**
     * Sets the value of the customsCode property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCustomsCode(String value) {
	this.customsCode = value;
    }

    /**
     * Gets the value of the cbeCode property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCbeCode() {
	return cbeCode;
    }

    /**
     * Sets the value of the cbeCode property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCbeCode(String value) {
	this.cbeCode = value;
    }

    /**
     * Gets the value of the cbeName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCbeName() {
	return cbeName;
    }

    /**
     * Sets the value of the cbeName property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCbeName(String value) {
	this.cbeName = value;
    }

    /**
     * Gets the value of the ecpCode property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getEcpCode() {
	return ecpCode;
    }

    /**
     * Sets the value of the ecpCode property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setEcpCode(String value) {
	this.ecpCode = value;
    }

    /**
     * Gets the value of the ecpName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getEcpName() {
	return ecpName;
    }

    /**
     * Sets the value of the ecpName property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setEcpName(String value) {
	this.ecpName = value;
    }

    /**
     * Gets the value of the customer property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCustomer() {
	return customer;
    }

    /**
     * Sets the value of the customer property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCustomer(String value) {
	this.customer = value;
    }

    /**
     * Gets the value of the idType property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getIdType() {
	return idType;
    }

    /**
     * Sets the value of the idType property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setIdType(String value) {
	this.idType = value;
    }

    /**
     * Gets the value of the customerId property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCustomerId() {
	return customerId;
    }

    /**
     * Sets the value of the customerId property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCustomerId(String value) {
	this.customerId = value;
    }

    /**
     * Gets the value of the orderNo property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getOrderNo() {
	return orderNo;
    }

    /**
     * Sets the value of the orderNo property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setOrderNo(String value) {
	this.orderNo = value;
    }

    /**
     * Gets the value of the charge property.
     * 
     * @return possible object is {@link BigDecimal }
     * 
     */
    public BigDecimal getCharge() {
	return charge;
    }

    /**
     * Sets the value of the charge property.
     * 
     * @param value
     *            allowed object is {@link BigDecimal }
     * 
     */
    public void setCharge(BigDecimal value) {
	this.charge = value;
    }

    /**
     * Gets the value of the goodsValue property.
     * 
     * @return possible object is {@link BigDecimal }
     * 
     */
    public BigDecimal getGoodsValue() {
	return goodsValue;
    }

    /**
     * Sets the value of the goodsValue property.
     * 
     * @param value
     *            allowed object is {@link BigDecimal }
     * 
     */
    public void setGoodsValue(BigDecimal value) {
	this.goodsValue = value;
    }

    /**
     * Gets the value of the freight property.
     * 
     * @return possible object is {@link BigDecimal }
     * 
     */
    public BigDecimal getFreight() {
	return freight;
    }

    /**
     * Sets the value of the freight property.
     * 
     * @param value
     *            allowed object is {@link BigDecimal }
     * 
     */
    public void setFreight(BigDecimal value) {
	this.freight = value;
    }

    /**
     * Gets the value of the other property.
     * 
     * @return possible object is {@link BigDecimal }
     * 
     */
    public BigDecimal getOther() {
	return other;
    }

    /**
     * Sets the value of the other property.
     * 
     * @param value
     *            allowed object is {@link BigDecimal }
     * 
     */
    public void setOther(BigDecimal value) {
	this.other = value;
    }

    /**
     * Gets the value of the tax property.
     * 
     * @return possible object is {@link BigDecimal }
     * 
     */
    public BigDecimal getTax() {
	return tax;
    }

    /**
     * Sets the value of the tax property.
     * 
     * @param value
     *            allowed object is {@link BigDecimal }
     * 
     */
    public void setTax(BigDecimal value) {
	this.tax = value;
    }

    /**
     * Gets the value of the shipper property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getShipper() {
	return shipper;
    }

    /**
     * Sets the value of the shipper property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setShipper(String value) {
	this.shipper = value;
    }

    /**
     * Gets the value of the shipperAddress property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getShipperAddress() {
	return shipperAddress;
    }

    /**
     * Sets the value of the shipperAddress property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setShipperAddress(String value) {
	this.shipperAddress = value;
    }

    /**
     * Gets the value of the shipperTelephone property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getShipperTelephone() {
	return shipperTelephone;
    }

    /**
     * Sets the value of the shipperTelephone property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setShipperTelephone(String value) {
	this.shipperTelephone = value;
    }

    /**
     * Gets the value of the shipperCountry property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getShipperCountry() {
	return shipperCountry;
    }

    /**
     * Sets the value of the shipperCountry property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setShipperCountry(String value) {
	this.shipperCountry = value;
    }

    /**
     * Gets the value of the consignee property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getConsignee() {
	return consignee;
    }

    /**
     * Sets the value of the consignee property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setConsignee(String value) {
	this.consignee = value;
    }

    /**
     * Gets the value of the consigneeAddress property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getConsigneeAddress() {
	return consigneeAddress;
    }

    /**
     * Sets the value of the consigneeAddress property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setConsigneeAddress(String value) {
	this.consigneeAddress = value;
    }

    /**
     * Gets the value of the consigneeTelephone property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getConsigneeTelephone() {
	return consigneeTelephone;
    }

    /**
     * Sets the value of the consigneeTelephone property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setConsigneeTelephone(String value) {
	this.consigneeTelephone = value;
    }

    /**
     * Gets the value of the consigneeCountry property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getConsigneeCountry() {
	return consigneeCountry;
    }

    /**
     * Sets the value of the consigneeCountry property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setConsigneeCountry(String value) {
	this.consigneeCountry = value;
    }

    /**
     * Gets the value of the ieType property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getIeType() {
	return ieType;
    }

    /**
     * Sets the value of the ieType property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setIeType(String value) {
	this.ieType = value;
    }

    /**
     * Gets the value of the compareFlag property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCompareFlag() {
	return compareFlag;
    }

    /**
     * Sets the value of the compareFlag property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCompareFlag(String value) {
	this.compareFlag = value;
    }

    /**
     * Gets the value of the note property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getNote() {
	return note;
    }

    /**
     * Sets the value of the note property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setNote(String value) {
	this.note = value;
    }

    /**
     * Gets the value of the declareDate property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDeclareDate() {
	return declareDate;
    }

    /**
     * Sets the value of the declareDate property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setDeclareDate(String value) {
	this.declareDate = value;
    }

    /**
     * Gets the value of the applyUser property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getApplyUser() {
	return applyUser;
    }

    /**
     * Sets the value of the applyUser property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setApplyUser(String value) {
	this.applyUser = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getStatus() {
	return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setStatus(String value) {
	this.status = value;
    }

    /**
     * Gets the value of the approveMan property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getApproveMan() {
	return approveMan;
    }

    /**
     * Sets the value of the approveMan property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setApproveMan(String value) {
	this.approveMan = value;
    }

    /**
     * Gets the value of the approveTime property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getApproveTime() {
	return approveTime;
    }

    /**
     * Sets the value of the approveTime property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setApproveTime(String value) {
	this.approveTime = value;
    }

    /**
     * Gets the value of the approveOpinion property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getApproveOpinion() {
	return approveOpinion;
    }

    /**
     * Sets the value of the approveOpinion property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setApproveOpinion(String value) {
	this.approveOpinion = value;
    }

    /**
     * Gets the value of the updateTime property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getUpdateTime() {
	return updateTime;
    }

    /**
     * Sets the value of the updateTime property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setUpdateTime(String value) {
	this.updateTime = value;
    }

    /**
     * Gets the value of the buildStatus property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getBuildStatus() {
	return buildStatus;
    }

    /**
     * Sets the value of the buildStatus property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setBuildStatus(String value) {
	this.buildStatus = value;
    }

    /**
     * Gets the value of the indbTime property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getIndbTime() {
	return indbTime;
    }

    /**
     * Sets the value of the indbTime property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setIndbTime(String value) {
	this.indbTime = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCurrency() {
	return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCurrency(String value) {
	this.currency = value;
    }

    /**
     * Gets the value of the batchNumbers property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getBatchNumbers() {
	return batchNumbers;
    }

    /**
     * Sets the value of the batchNumbers property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setBatchNumbers(String value) {
	this.batchNumbers = value;
    }

    /**
     * Gets the value of the totalLogisticsNo property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTotalLogisticsNo() {
	return totalLogisticsNo;
    }

    /**
     * Sets the value of the totalLogisticsNo property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setTotalLogisticsNo(String value) {
	this.totalLogisticsNo = value;
    }

    /**
     * Gets the value of the tradeCountry property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTradeCountry() {
	return tradeCountry;
    }

    /**
     * Sets the value of the tradeCountry property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setTradeCountry(String value) {
	this.tradeCountry = value;
    }

    /**
     * Gets the value of the agentCode property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getAgentCode() {
	return agentCode;
    }

    /**
     * Sets the value of the agentCode property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setAgentCode(String value) {
	this.agentCode = value;
    }

    /**
     * Gets the value of the agentName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getAgentName() {
	return agentName;
    }

    /**
     * Sets the value of the agentName property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setAgentName(String value) {
	this.agentName = value;
    }

    public String getPaymentCode() {
	return paymentCode;
    }

    public void setPaymentCode(String paymentCode) {
	this.paymentCode = paymentCode;
    }

    public String getPaymentName() {
	return paymentName;
    }

    public void setPaymentName(String paymentName) {
	this.paymentName = paymentName;
    }

    public String getPaymentNo() {
	return paymentNo;
    }

    public void setPaymentNo(String paymentNo) {
	this.paymentNo = paymentNo;
    }

    public String getLogisticsCode() {
	return logisticsCode;
    }

    public void setLogisticsCode(String logisticsCode) {
	this.logisticsCode = logisticsCode;
    }

    public String getLogisticsName() {
	return logisticsName;
    }

    public void setLogisticsName(String logisticsName) {
	this.logisticsName = logisticsName;
    }

    public String getLogisticsNo() {
	return logisticsNo;
    }

    public void setLogisticsNo(String logisticsNo) {
	this.logisticsNo = logisticsNo;
    }

    public String getRecDetail() {
	return recDetail;
    }

    public void setRecDetail(String recDetail) {
	this.recDetail = recDetail;
    }

}
