//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.22 at 07:28:24 下午 CST 
//

package com.cneport.ecss.exchange.service.entity;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 订单支付/物流
 * 
 * <p>
 * Java class for OrderPaymentLogistics complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="OrderPaymentLogistics">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="seqNo">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="36"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="paymentCode">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="paymentName">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="paymentType">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="paymentNo">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="40"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="logisticsCode">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="logisticsName">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="logisticsNo">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="trackNo">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OrderPaymentLogistics", propOrder = { "seqNo", "paymentCode",
	"paymentName", "paymentType", "paymentNo", "logisticsCode",
	"logisticsName", "logisticsNo", "trackNo" })
public class OrderPaymentLogistics {

    @XmlElement(required = true)
    protected String seqNo;
    @XmlElement(required = true)
    protected String paymentCode;
    @XmlElement(required = true)
    protected String paymentName;
    @XmlElement(required = true)
    protected String paymentType;
    @XmlElement(required = true)
    protected String paymentNo;
    @XmlElement(required = true)
    protected String logisticsCode;
    @XmlElement(required = true)
    protected String logisticsName;
    @XmlElement(required = true)
    protected String logisticsNo;
    @XmlElement(required = true)
    protected String trackNo;

    /**
     * Gets the value of the seqNo property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSeqNo() {
	return seqNo;
    }

    /**
     * Sets the value of the seqNo property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setSeqNo(String value) {
	this.seqNo = value;
    }

    /**
     * Gets the value of the paymentCode property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getPaymentCode() {
	return paymentCode;
    }

    /**
     * Sets the value of the paymentCode property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setPaymentCode(String value) {
	this.paymentCode = value;
    }

    /**
     * Gets the value of the paymentName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getPaymentName() {
	return paymentName;
    }

    /**
     * Sets the value of the paymentName property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setPaymentName(String value) {
	this.paymentName = value;
    }

    /**
     * Gets the value of the paymentType property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getPaymentType() {
	return paymentType;
    }

    /**
     * Sets the value of the paymentType property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setPaymentType(String value) {
	this.paymentType = value;
    }

    /**
     * Gets the value of the paymentNo property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getPaymentNo() {
	return paymentNo;
    }

    /**
     * Sets the value of the paymentNo property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setPaymentNo(String value) {
	this.paymentNo = value;
    }

    /**
     * Gets the value of the logisticsCode property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getLogisticsCode() {
	return logisticsCode;
    }

    /**
     * Sets the value of the logisticsCode property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setLogisticsCode(String value) {
	this.logisticsCode = value;
    }

    /**
     * Gets the value of the logisticsName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getLogisticsName() {
	return logisticsName;
    }

    /**
     * Sets the value of the logisticsName property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setLogisticsName(String value) {
	this.logisticsName = value;
    }

    /**
     * Gets the value of the logisticsNo property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getLogisticsNo() {
	return logisticsNo;
    }

    /**
     * Sets the value of the logisticsNo property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setLogisticsNo(String value) {
	this.logisticsNo = value;
    }

    /**
     * Gets the value of the trackNo property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTrackNo() {
	return trackNo;
    }

    /**
     * Sets the value of the trackNo property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setTrackNo(String value) {
	this.trackNo = value;
    }

}
