//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.22 at 07:28:24 下午 CST 
//

package com.cneport.ecss.exchange.service.entity;

import java.math.BigDecimal;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 订单表体
 * 
 * <p>
 * Java class for OrderList complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="OrderList">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="seqNo">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="36"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="listNo">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="18"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="itemNo">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="goodsNo">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="shelfGoodsName">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="250"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="describe">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="250"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="price" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="currency">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="quantity" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="unit">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="country">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="discount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="flag">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="codeTs">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="taxCode">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="8"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="goodsName">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="250"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="goodsModel">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="250"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="priceTotal" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="purposeCode">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="wasteMaterials">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OrderList", propOrder = { "seqNo", "listNo", "itemNo",
	"goodsNo", "shelfGoodsName", "describe", "price", "currency",
	"quantity", "unit", "country", "discount", "flag", "codeTs", "taxCode",
	"goodsName", "goodsModel", "priceTotal", "purposeCode",
	"wasteMaterials" })
public class OrderList {

    @XmlElement(required = true)
    protected String seqNo;
    @XmlElement(required = true)
    protected String listNo;
    @XmlElement(required = true)
    protected String itemNo;
    @XmlElement(required = true)
    protected String goodsNo;
    @XmlElement(required = true)
    protected String shelfGoodsName;
    @XmlElement(required = true)
    protected String describe;
    @XmlElement(required = true)
    protected BigDecimal price;
    @XmlElement(required = true)
    protected String currency;
    @XmlElement(required = true)
    protected BigDecimal quantity;
    @XmlElement(required = true)
    protected String unit;
    @XmlElement(required = true)
    protected String country;
    @XmlElement(required = true)
    protected BigDecimal discount;
    @XmlElement(required = true)
    protected String flag;
    @XmlElement(required = true)
    protected String codeTs;
    @XmlElement(required = true)
    protected String taxCode;
    @XmlElement(required = true)
    protected String goodsName;
    @XmlElement(required = true)
    protected String goodsModel;
    @XmlElement(required = true)
    protected BigDecimal priceTotal;
    @XmlElement(required = true)
    protected String purposeCode;
    @XmlElement(required = true)
    protected String wasteMaterials;

    /**
     * Gets the value of the seqNo property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSeqNo() {
	return seqNo;
    }

    /**
     * Sets the value of the seqNo property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setSeqNo(String value) {
	this.seqNo = value;
    }

    /**
     * Gets the value of the listNo property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getListNo() {
	return listNo;
    }

    /**
     * Sets the value of the listNo property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setListNo(String value) {
	this.listNo = value;
    }

    /**
     * Gets the value of the itemNo property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getItemNo() {
	return itemNo;
    }

    /**
     * Sets the value of the itemNo property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setItemNo(String value) {
	this.itemNo = value;
    }

    /**
     * Gets the value of the goodsNo property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getGoodsNo() {
	return goodsNo;
    }

    /**
     * Sets the value of the goodsNo property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setGoodsNo(String value) {
	this.goodsNo = value;
    }

    /**
     * Gets the value of the shelfGoodsName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getShelfGoodsName() {
	return shelfGoodsName;
    }

    /**
     * Sets the value of the shelfGoodsName property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setShelfGoodsName(String value) {
	this.shelfGoodsName = value;
    }

    /**
     * Gets the value of the describe property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDescribe() {
	return describe;
    }

    /**
     * Sets the value of the describe property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setDescribe(String value) {
	this.describe = value;
    }

    /**
     * Gets the value of the price property.
     * 
     * @return possible object is {@link BigDecimal }
     * 
     */
    public BigDecimal getPrice() {
	return price;
    }

    /**
     * Sets the value of the price property.
     * 
     * @param value
     *            allowed object is {@link BigDecimal }
     * 
     */
    public void setPrice(BigDecimal value) {
	this.price = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCurrency() {
	return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCurrency(String value) {
	this.currency = value;
    }

    /**
     * Gets the value of the quantity property.
     * 
     * @return possible object is {@link BigDecimal }
     * 
     */
    public BigDecimal getQuantity() {
	return quantity;
    }

    /**
     * Sets the value of the quantity property.
     * 
     * @param value
     *            allowed object is {@link BigDecimal }
     * 
     */
    public void setQuantity(BigDecimal value) {
	this.quantity = value;
    }

    /**
     * Gets the value of the unit property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getUnit() {
	return unit;
    }

    /**
     * Sets the value of the unit property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setUnit(String value) {
	this.unit = value;
    }

    /**
     * Gets the value of the country property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCountry() {
	return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCountry(String value) {
	this.country = value;
    }

    /**
     * Gets the value of the discount property.
     * 
     * @return possible object is {@link BigDecimal }
     * 
     */
    public BigDecimal getDiscount() {
	return discount;
    }

    /**
     * Sets the value of the discount property.
     * 
     * @param value
     *            allowed object is {@link BigDecimal }
     * 
     */
    public void setDiscount(BigDecimal value) {
	this.discount = value;
    }

    /**
     * Gets the value of the flag property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getFlag() {
	return flag;
    }

    /**
     * Sets the value of the flag property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setFlag(String value) {
	this.flag = value;
    }

    /**
     * Gets the value of the codeTs property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCodeTs() {
	return codeTs;
    }

    /**
     * Sets the value of the codeTs property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCodeTs(String value) {
	this.codeTs = value;
    }

    /**
     * Gets the value of the taxCode property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTaxCode() {
	return taxCode;
    }

    /**
     * Sets the value of the taxCode property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setTaxCode(String value) {
	this.taxCode = value;
    }

    /**
     * Gets the value of the goodsName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getGoodsName() {
	return goodsName;
    }

    /**
     * Sets the value of the goodsName property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setGoodsName(String value) {
	this.goodsName = value;
    }

    /**
     * Gets the value of the goodsModel property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getGoodsModel() {
	return goodsModel;
    }

    /**
     * Sets the value of the goodsModel property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setGoodsModel(String value) {
	this.goodsModel = value;
    }

    /**
     * Gets the value of the priceTotal property.
     * 
     * @return possible object is {@link BigDecimal }
     * 
     */
    public BigDecimal getPriceTotal() {
	return priceTotal;
    }

    /**
     * Sets the value of the priceTotal property.
     * 
     * @param value
     *            allowed object is {@link BigDecimal }
     * 
     */
    public void setPriceTotal(BigDecimal value) {
	this.priceTotal = value;
    }

    /**
     * Gets the value of the purposeCode property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getPurposeCode() {
	return purposeCode;
    }

    /**
     * Sets the value of the purposeCode property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setPurposeCode(String value) {
	this.purposeCode = value;
    }

    /**
     * Gets the value of the wasteMaterials property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getWasteMaterials() {
	return wasteMaterials;
    }

    /**
     * Sets the value of the wasteMaterials property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setWasteMaterials(String value) {
	this.wasteMaterials = value;
    }

}
