//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.28 at 05:18:17 ���� CST 
//

package com.cneport.ecss.exchange.service.entity;

import java.math.BigDecimal;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="seqNo">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="36"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="customsCode">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="declareDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="paymentCode">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="paymentName">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="200"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="paymentType">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="paymentNo">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="40"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="charge" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="currency">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="customerFlag">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="customerData">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="compareFlag">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ieType">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="note">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1000"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="status">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="18"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="approveMan">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="18"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="approveTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="approveOpinion">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1024"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="updateTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="companyCode">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="orderNo">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="30"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ecpCode">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ecpName">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="200"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="indbTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "seqNo", "customsCode", "declareDate",
	"paymentCode", "paymentName", "paymentType", "paymentNo", "charge",
	"currency", "customerFlag", "customerData", "compareFlag", "ieType",
	"note", "status", "approveMan", "approveTime", "approveOpinion",
	"updateTime", "companyCode", "orderNo", "ecpCode", "ecpName",
	"indbTime" })
@XmlRootElement(name = "PaymentInformation")
public class PaymentInformation {

    @XmlElement(required = true)
    protected String seqNo;
    @XmlElement(required = true)
    protected String customsCode;
    @XmlElement(required = true)
    protected String declareDate;
    @XmlElement(required = true)
    protected String paymentCode;
    @XmlElement(required = true)
    protected String paymentName;
    @XmlElement(required = true)
    protected String paymentType;
    @XmlElement(required = true)
    protected String paymentNo;
    @XmlElement(required = true)
    protected BigDecimal charge;
    @XmlElement(required = true)
    protected String currency;
    @XmlElement(required = true)
    protected String customerFlag;
    @XmlElement(required = true)
    protected String customerData;
    @XmlElement(required = true)
    protected String compareFlag;
    @XmlElement(required = true)
    protected String ieType;
    @XmlElement(required = true)
    protected String note;
    @XmlElement(required = true)
    protected String status;
    @XmlElement(required = true)
    protected String approveMan;
    @XmlElement(required = true)
    protected String approveTime;
    @XmlElement(required = true)
    protected String approveOpinion;
    @XmlElement(required = true)
    protected String updateTime;
    @XmlElement(required = true)
    protected String companyCode;
    @XmlElement(required = true)
    protected String orderNo;
    @XmlElement(required = true)
    protected String ecpCode;
    @XmlElement(required = true)
    protected String ecpName;
    @XmlElement(required = true)
    protected String indbTime;

    /**
     * Gets the value of the seqNo property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSeqNo() {
	return seqNo;
    }

    /**
     * Sets the value of the seqNo property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setSeqNo(String value) {
	this.seqNo = value;
    }

    /**
     * Gets the value of the customsCode property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCustomsCode() {
	return customsCode;
    }

    /**
     * Sets the value of the customsCode property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCustomsCode(String value) {
	this.customsCode = value;
    }

    /**
     * Gets the value of the declareDate property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDeclareDate() {
	return declareDate;
    }

    /**
     * Sets the value of the declareDate property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setDeclareDate(String value) {
	this.declareDate = value;
    }

    /**
     * Gets the value of the paymentCode property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getPaymentCode() {
	return paymentCode;
    }

    /**
     * Sets the value of the paymentCode property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setPaymentCode(String value) {
	this.paymentCode = value;
    }

    /**
     * Gets the value of the paymentName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getPaymentName() {
	return paymentName;
    }

    /**
     * Sets the value of the paymentName property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setPaymentName(String value) {
	this.paymentName = value;
    }

    /**
     * Gets the value of the paymentType property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getPaymentType() {
	return paymentType;
    }

    /**
     * Sets the value of the paymentType property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setPaymentType(String value) {
	this.paymentType = value;
    }

    /**
     * Gets the value of the paymentNo property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getPaymentNo() {
	return paymentNo;
    }

    /**
     * Sets the value of the paymentNo property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setPaymentNo(String value) {
	this.paymentNo = value;
    }

    /**
     * Gets the value of the charge property.
     * 
     * @return possible object is {@link BigDecimal }
     * 
     */
    public BigDecimal getCharge() {
	return charge;
    }

    /**
     * Sets the value of the charge property.
     * 
     * @param value
     *            allowed object is {@link BigDecimal }
     * 
     */
    public void setCharge(BigDecimal value) {
	this.charge = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCurrency() {
	return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCurrency(String value) {
	this.currency = value;
    }

    /**
     * Gets the value of the customerFlag property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCustomerFlag() {
	return customerFlag;
    }

    /**
     * Sets the value of the customerFlag property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCustomerFlag(String value) {
	this.customerFlag = value;
    }

    /**
     * Gets the value of the customerData property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCustomerData() {
	return customerData;
    }

    /**
     * Sets the value of the customerData property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCustomerData(String value) {
	this.customerData = value;
    }

    /**
     * Gets the value of the compareFlag property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCompareFlag() {
	return compareFlag;
    }

    /**
     * Sets the value of the compareFlag property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCompareFlag(String value) {
	this.compareFlag = value;
    }

    /**
     * Gets the value of the ieType property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getIeType() {
	return ieType;
    }

    /**
     * Sets the value of the ieType property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setIeType(String value) {
	this.ieType = value;
    }

    /**
     * Gets the value of the note property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getNote() {
	return note;
    }

    /**
     * Sets the value of the note property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setNote(String value) {
	this.note = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getStatus() {
	return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setStatus(String value) {
	this.status = value;
    }

    /**
     * Gets the value of the approveMan property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getApproveMan() {
	return approveMan;
    }

    /**
     * Sets the value of the approveMan property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setApproveMan(String value) {
	this.approveMan = value;
    }

    /**
     * Gets the value of the approveTime property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getApproveTime() {
	return approveTime;
    }

    /**
     * Sets the value of the approveTime property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setApproveTime(String value) {
	this.approveTime = value;
    }

    /**
     * Gets the value of the approveOpinion property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getApproveOpinion() {
	return approveOpinion;
    }

    /**
     * Sets the value of the approveOpinion property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setApproveOpinion(String value) {
	this.approveOpinion = value;
    }

    /**
     * Gets the value of the updateTime property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getUpdateTime() {
	return updateTime;
    }

    /**
     * Sets the value of the updateTime property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setUpdateTime(String value) {
	this.updateTime = value;
    }

    /**
     * Gets the value of the companyCode property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCompanyCode() {
	return companyCode;
    }

    /**
     * Sets the value of the companyCode property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCompanyCode(String value) {
	this.companyCode = value;
    }

    /**
     * Gets the value of the orderNo property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getOrderNo() {
	return orderNo;
    }

    /**
     * Sets the value of the orderNo property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setOrderNo(String value) {
	this.orderNo = value;
    }

    /**
     * Gets the value of the ecpCode property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getEcpCode() {
	return ecpCode;
    }

    /**
     * Sets the value of the ecpCode property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setEcpCode(String value) {
	this.ecpCode = value;
    }

    /**
     * Gets the value of the ecpName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getEcpName() {
	return ecpName;
    }

    /**
     * Sets the value of the ecpName property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setEcpName(String value) {
	this.ecpName = value;
    }

    /**
     * Gets the value of the indbTime property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getIndbTime() {
	return indbTime;
    }

    /**
     * Sets the value of the indbTime property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setIndbTime(String value) {
	this.indbTime = value;
    }

}
