//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.28 at 05:18:17 ���� CST 
//

package com.cneport.ecss.exchange.service.entity;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PersonalDeclareHead" type="{}PersonalDeclareHead"/>
 *         &lt;element name="PersonalDeclareList" type="{}PersonalDeclareList" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "personalDeclareHead", "personalDeclareList" })
@XmlRootElement(name = "PersonalDeclare")
public class PersonalDeclare {

    @XmlElement(name = "PersonalDeclareHead", required = true)
    protected PersonalDeclareHead personalDeclareHead;
    @XmlElement(name = "PersonalDeclareList")
    protected List<PersonalDeclareList> personalDeclareList;

    /**
     * Gets the value of the personalDeclareHead property.
     * 
     * @return possible object is {@link PersonalDeclareHead }
     * 
     */
    public PersonalDeclareHead getPersonalDeclareHead() {
	return personalDeclareHead;
    }

    /**
     * Sets the value of the personalDeclareHead property.
     * 
     * @param value
     *            allowed object is {@link PersonalDeclareHead }
     * 
     */
    public void setPersonalDeclareHead(PersonalDeclareHead value) {
	this.personalDeclareHead = value;
    }

    /**
     * Gets the value of the personalDeclareList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the personalDeclareList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getPersonalDeclareList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PersonalDeclareList }
     * 
     * 
     */
    public List<PersonalDeclareList> getPersonalDeclareList() {
	if (personalDeclareList == null) {
	    personalDeclareList = new ArrayList<PersonalDeclareList>();
	}
	return this.personalDeclareList;
    }

}
