//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.28 at 05:18:17 ���� CST 
//

package com.cneport.ecss.exchange.service.entity;

import java.math.BigDecimal;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * �����Ʒ�걨������
 * 
 * <p>
 * Java class for PersonalDeclareList complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="PersonalDeclareList">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="seqNo">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="36"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="listNo">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="18"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="goodsNo">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="goodsName">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="250"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="codeTs">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="goodsModel">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="250"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="taxCode">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="8"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="price" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="currency">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="rmbPrice" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="taxRate" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="tax" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="quantity" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="unit">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="itemNo">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="registerPrice" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="dutiablePrice" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="taxPriceAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="taxPrice" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="priceTotal" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="shelfGoodsName">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="250"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="limitationGoodsCode">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="unit1">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="unit2">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PersonalDeclareList", propOrder = { "seqNo", "listNo",
	"goodsNo", "goodsName", "codeTs", "goodsModel", "taxCode", "price",
	"currency", "rmbPrice", "taxRate", "tax", "quantity", "unit", "itemNo",
	"registerPrice", "dutiablePrice", "taxPriceAmount", "taxPrice",
	"priceTotal", "shelfGoodsName", "limitationGoodsCode", "unit1", "unit2" })
public class PersonalDeclareList {

    @XmlElement(required = true)
    protected String seqNo;
    @XmlElement(required = true)
    protected String listNo;
    @XmlElement(required = true)
    protected String goodsNo;
    @XmlElement(required = true)
    protected String goodsName;
    @XmlElement(required = true)
    protected String codeTs;
    @XmlElement(required = true)
    protected String goodsModel;
    @XmlElement(required = true)
    protected String taxCode;
    @XmlElement(required = true)
    protected BigDecimal price;
    @XmlElement(required = true)
    protected String currency;
    @XmlElement(required = true)
    protected BigDecimal rmbPrice;
    @XmlElement(required = true)
    protected BigDecimal taxRate;
    @XmlElement(required = true)
    protected BigDecimal tax;
    @XmlElement(required = true)
    protected BigDecimal quantity;
    @XmlElement(required = true)
    protected String unit;
    @XmlElement(required = true)
    protected String itemNo;
    @XmlElement(required = true)
    protected BigDecimal registerPrice;
    @XmlElement(required = true)
    protected BigDecimal dutiablePrice;
    @XmlElement(required = true)
    protected BigDecimal taxPriceAmount;
    @XmlElement(required = true)
    protected BigDecimal taxPrice;
    @XmlElement(required = true)
    protected BigDecimal priceTotal;
    @XmlElement(required = true)
    protected String shelfGoodsName;
    @XmlElement(required = true)
    protected String limitationGoodsCode;
    @XmlElement(required = true)
    protected String unit1;
    @XmlElement(required = true)
    protected String unit2;

    /**
     * Gets the value of the seqNo property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSeqNo() {
	return seqNo;
    }

    /**
     * Sets the value of the seqNo property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setSeqNo(String value) {
	this.seqNo = value;
    }

    /**
     * Gets the value of the listNo property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getListNo() {
	return listNo;
    }

    /**
     * Sets the value of the listNo property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setListNo(String value) {
	this.listNo = value;
    }

    /**
     * Gets the value of the goodsNo property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getGoodsNo() {
	return goodsNo;
    }

    /**
     * Sets the value of the goodsNo property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setGoodsNo(String value) {
	this.goodsNo = value;
    }

    /**
     * Gets the value of the goodsName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getGoodsName() {
	return goodsName;
    }

    /**
     * Sets the value of the goodsName property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setGoodsName(String value) {
	this.goodsName = value;
    }

    /**
     * Gets the value of the codeTs property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCodeTs() {
	return codeTs;
    }

    /**
     * Sets the value of the codeTs property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCodeTs(String value) {
	this.codeTs = value;
    }

    /**
     * Gets the value of the goodsModel property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getGoodsModel() {
	return goodsModel;
    }

    /**
     * Sets the value of the goodsModel property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setGoodsModel(String value) {
	this.goodsModel = value;
    }

    /**
     * Gets the value of the taxCode property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTaxCode() {
	return taxCode;
    }

    /**
     * Sets the value of the taxCode property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setTaxCode(String value) {
	this.taxCode = value;
    }

    /**
     * Gets the value of the price property.
     * 
     * @return possible object is {@link BigDecimal }
     * 
     */
    public BigDecimal getPrice() {
	return price;
    }

    /**
     * Sets the value of the price property.
     * 
     * @param value
     *            allowed object is {@link BigDecimal }
     * 
     */
    public void setPrice(BigDecimal value) {
	this.price = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCurrency() {
	return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCurrency(String value) {
	this.currency = value;
    }

    /**
     * Gets the value of the rmbPrice property.
     * 
     * @return possible object is {@link BigDecimal }
     * 
     */
    public BigDecimal getRmbPrice() {
	return rmbPrice;
    }

    /**
     * Sets the value of the rmbPrice property.
     * 
     * @param value
     *            allowed object is {@link BigDecimal }
     * 
     */
    public void setRmbPrice(BigDecimal value) {
	this.rmbPrice = value;
    }

    /**
     * Gets the value of the taxRate property.
     * 
     * @return possible object is {@link BigDecimal }
     * 
     */
    public BigDecimal getTaxRate() {
	return taxRate;
    }

    /**
     * Sets the value of the taxRate property.
     * 
     * @param value
     *            allowed object is {@link BigDecimal }
     * 
     */
    public void setTaxRate(BigDecimal value) {
	this.taxRate = value;
    }

    /**
     * Gets the value of the tax property.
     * 
     * @return possible object is {@link BigDecimal }
     * 
     */
    public BigDecimal getTax() {
	return tax;
    }

    /**
     * Sets the value of the tax property.
     * 
     * @param value
     *            allowed object is {@link BigDecimal }
     * 
     */
    public void setTax(BigDecimal value) {
	this.tax = value;
    }

    /**
     * Gets the value of the quantity property.
     * 
     * @return possible object is {@link BigDecimal }
     * 
     */
    public BigDecimal getQuantity() {
	return quantity;
    }

    /**
     * Sets the value of the quantity property.
     * 
     * @param value
     *            allowed object is {@link BigDecimal }
     * 
     */
    public void setQuantity(BigDecimal value) {
	this.quantity = value;
    }

    /**
     * Gets the value of the unit property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getUnit() {
	return unit;
    }

    /**
     * Sets the value of the unit property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setUnit(String value) {
	this.unit = value;
    }

    /**
     * Gets the value of the itemNo property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getItemNo() {
	return itemNo;
    }

    /**
     * Sets the value of the itemNo property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setItemNo(String value) {
	this.itemNo = value;
    }

    /**
     * Gets the value of the registerPrice property.
     * 
     * @return possible object is {@link BigDecimal }
     * 
     */
    public BigDecimal getRegisterPrice() {
	return registerPrice;
    }

    /**
     * Sets the value of the registerPrice property.
     * 
     * @param value
     *            allowed object is {@link BigDecimal }
     * 
     */
    public void setRegisterPrice(BigDecimal value) {
	this.registerPrice = value;
    }

    /**
     * Gets the value of the dutiablePrice property.
     * 
     * @return possible object is {@link BigDecimal }
     * 
     */
    public BigDecimal getDutiablePrice() {
	return dutiablePrice;
    }

    /**
     * Sets the value of the dutiablePrice property.
     * 
     * @param value
     *            allowed object is {@link BigDecimal }
     * 
     */
    public void setDutiablePrice(BigDecimal value) {
	this.dutiablePrice = value;
    }

    /**
     * Gets the value of the taxPriceAmount property.
     * 
     * @return possible object is {@link BigDecimal }
     * 
     */
    public BigDecimal getTaxPriceAmount() {
	return taxPriceAmount;
    }

    /**
     * Sets the value of the taxPriceAmount property.
     * 
     * @param value
     *            allowed object is {@link BigDecimal }
     * 
     */
    public void setTaxPriceAmount(BigDecimal value) {
	this.taxPriceAmount = value;
    }

    /**
     * Gets the value of the taxPrice property.
     * 
     * @return possible object is {@link BigDecimal }
     * 
     */
    public BigDecimal getTaxPrice() {
	return taxPrice;
    }

    /**
     * Sets the value of the taxPrice property.
     * 
     * @param value
     *            allowed object is {@link BigDecimal }
     * 
     */
    public void setTaxPrice(BigDecimal value) {
	this.taxPrice = value;
    }

    /**
     * Gets the value of the priceTotal property.
     * 
     * @return possible object is {@link BigDecimal }
     * 
     */
    public BigDecimal getPriceTotal() {
	return priceTotal;
    }

    /**
     * Sets the value of the priceTotal property.
     * 
     * @param value
     *            allowed object is {@link BigDecimal }
     * 
     */
    public void setPriceTotal(BigDecimal value) {
	this.priceTotal = value;
    }

    /**
     * Gets the value of the shelfGoodsName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getShelfGoodsName() {
	return shelfGoodsName;
    }

    /**
     * Sets the value of the shelfGoodsName property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setShelfGoodsName(String value) {
	this.shelfGoodsName = value;
    }

    /**
     * Gets the value of the limitationGoodsCode property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getLimitationGoodsCode() {
	return limitationGoodsCode;
    }

    /**
     * Sets the value of the limitationGoodsCode property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setLimitationGoodsCode(String value) {
	this.limitationGoodsCode = value;
    }

    /**
     * Gets the value of the unit1 property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getUnit1() {
	return unit1;
    }

    /**
     * Sets the value of the unit1 property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setUnit1(String value) {
	this.unit1 = value;
    }

    /**
     * Gets the value of the unit2 property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getUnit2() {
	return unit2;
    }

    /**
     * Sets the value of the unit2 property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setUnit2(String value) {
	this.unit2 = value;
    }

}
