//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.28 at 05:18:17 ���� CST 
//

package com.cneport.ecss.exchange.service.entity;

import java.math.BigDecimal;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * �����Ʒ�걨����ͷ
 * 
 * <p>
 * Java class for PersonalDeclareHead complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="PersonalDeclareHead">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="seqNo">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="36"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="personalEntryId">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="18"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="operator">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="60"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="iePort">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="voy">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ieDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="totalShippedNumber">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="24"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="declarant">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="60"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="customsCode">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="orderNo">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="30"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ecpCode">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="40"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ecpName">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="logisticsCode">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="logisticsName">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="logisticsNo">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="consignee">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="60"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="telephone">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="30"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="idType">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="idNumber">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="60"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="country">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="taxAddress">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="255"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="taxTotal" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="checkNote">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="255"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="taxStatus">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="stockFlag">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="returnFlag">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="declareDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dischargeDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="status">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="18"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="approveMan">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="60"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="approveTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="approveOpinion">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1024"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="updateTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="distStat">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="controlledStatus">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="controlledDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="controlledType">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="indbTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cbeCode">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="cbeName">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="200"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="currency">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="packNum" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="wrapType">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="grossWeight" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="netWeight" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="manualReason">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="200"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="declareCode">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="declareName">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="255"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="modifyTimes" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="lmsNo">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="18"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="totalValue" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="totalValueRmb" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="reviewFlag">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="exceptionFlag">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PersonalDeclareHead", propOrder = { "seqNo",
	"personalEntryId", "operator", "iePort", "voy", "ieDate",
	"totalShippedNumber", "declarant", "customsCode", "orderNo", "ecpCode",
	"ecpName", "logisticsCode", "logisticsName", "logisticsNo",
	"consignee", "telephone", "idType", "idNumber", "country",
	"taxAddress", "taxTotal", "checkNote", "taxStatus", "stockFlag",
	"returnFlag", "declareDate", "dischargeDate", "status", "approveMan",
	"approveTime", "approveOpinion", "updateTime", "distStat",
	"controlledStatus", "controlledDate", "controlledType", "indbTime",
	"cbeCode", "cbeName", "currency", "packNum", "wrapType", "grossWeight",
	"netWeight", "manualReason", "declareCode", "declareName",
	"modifyTimes", "lmsNo", "totalValue", "totalValueRmb", "reviewFlag",
	"exceptionFlag" })
public class PersonalDeclareHead {

    @XmlElement(required = true)
    protected String seqNo;
    @XmlElement(required = true)
    protected String personalEntryId;
    @XmlElement(required = true)
    protected String operator;
    @XmlElement(required = true)
    protected String iePort;
    @XmlElement(required = true)
    protected String voy;
    @XmlElement(required = true)
    protected String ieDate;
    @XmlElement(required = true)
    protected String totalShippedNumber;
    @XmlElement(required = true)
    protected String declarant;
    @XmlElement(required = true)
    protected String customsCode;
    @XmlElement(required = true)
    protected String orderNo;
    @XmlElement(required = true)
    protected String ecpCode;
    @XmlElement(required = true)
    protected String ecpName;
    @XmlElement(required = true)
    protected String logisticsCode;
    @XmlElement(required = true)
    protected String logisticsName;
    @XmlElement(required = true)
    protected String logisticsNo;
    @XmlElement(required = true)
    protected String consignee;
    @XmlElement(required = true)
    protected String telephone;
    @XmlElement(required = true)
    protected String idType;
    @XmlElement(required = true)
    protected String idNumber;
    @XmlElement(required = true)
    protected String country;
    @XmlElement(required = true)
    protected String taxAddress;
    @XmlElement(required = true)
    protected BigDecimal taxTotal;
    @XmlElement(required = true)
    protected String checkNote;
    @XmlElement(required = true)
    protected String taxStatus;
    @XmlElement(required = true)
    protected String stockFlag;
    @XmlElement(required = true)
    protected String returnFlag;
    @XmlElement(required = true)
    protected String declareDate;
    @XmlElement(required = true)
    protected String dischargeDate;
    @XmlElement(required = true)
    protected String status;
    @XmlElement(required = true)
    protected String approveMan;
    @XmlElement(required = true)
    protected String approveTime;
    @XmlElement(required = true)
    protected String approveOpinion;
    @XmlElement(required = true)
    protected String updateTime;
    @XmlElement(required = true)
    protected String distStat;
    @XmlElement(required = true)
    protected String controlledStatus;
    @XmlElement(required = true)
    protected String controlledDate;
    @XmlElement(required = true)
    protected String controlledType;
    @XmlElement(required = true)
    protected String indbTime;
    @XmlElement(required = true)
    protected String cbeCode;
    @XmlElement(required = true)
    protected String cbeName;
    @XmlElement(required = true)
    protected String currency;
    @XmlElement(required = true)
    protected BigDecimal packNum;
    @XmlElement(required = true)
    protected String wrapType;
    @XmlElement(required = true)
    protected BigDecimal grossWeight;
    @XmlElement(required = true)
    protected BigDecimal netWeight;
    @XmlElement(required = true)
    protected String manualReason;
    @XmlElement(required = true)
    protected String declareCode;
    @XmlElement(required = true)
    protected String declareName;
    @XmlElement(required = true)
    protected BigDecimal modifyTimes;
    @XmlElement(required = true)
    protected String lmsNo;
    @XmlElement(required = true)
    protected BigDecimal totalValue;
    @XmlElement(required = true)
    protected BigDecimal totalValueRmb;
    @XmlElement(required = true)
    protected String reviewFlag;
    @XmlElement(required = true)
    protected String exceptionFlag;

    /**
     * Gets the value of the seqNo property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSeqNo() {
	return seqNo;
    }

    /**
     * Sets the value of the seqNo property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setSeqNo(String value) {
	this.seqNo = value;
    }

    /**
     * Gets the value of the personalEntryId property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getPersonalEntryId() {
	return personalEntryId;
    }

    /**
     * Sets the value of the personalEntryId property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setPersonalEntryId(String value) {
	this.personalEntryId = value;
    }

    /**
     * Gets the value of the operator property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getOperator() {
	return operator;
    }

    /**
     * Sets the value of the operator property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setOperator(String value) {
	this.operator = value;
    }

    /**
     * Gets the value of the iePort property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getIePort() {
	return iePort;
    }

    /**
     * Sets the value of the iePort property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setIePort(String value) {
	this.iePort = value;
    }

    /**
     * Gets the value of the voy property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getVoy() {
	return voy;
    }

    /**
     * Sets the value of the voy property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setVoy(String value) {
	this.voy = value;
    }

    /**
     * Gets the value of the ieDate property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getIeDate() {
	return ieDate;
    }

    /**
     * Sets the value of the ieDate property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setIeDate(String value) {
	this.ieDate = value;
    }

    /**
     * Gets the value of the totalShippedNumber property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTotalShippedNumber() {
	return totalShippedNumber;
    }

    /**
     * Sets the value of the totalShippedNumber property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setTotalShippedNumber(String value) {
	this.totalShippedNumber = value;
    }

    /**
     * Gets the value of the declarant property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDeclarant() {
	return declarant;
    }

    /**
     * Sets the value of the declarant property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setDeclarant(String value) {
	this.declarant = value;
    }

    /**
     * Gets the value of the customsCode property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCustomsCode() {
	return customsCode;
    }

    /**
     * Sets the value of the customsCode property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCustomsCode(String value) {
	this.customsCode = value;
    }

    /**
     * Gets the value of the orderNo property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getOrderNo() {
	return orderNo;
    }

    /**
     * Sets the value of the orderNo property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setOrderNo(String value) {
	this.orderNo = value;
    }

    /**
     * Gets the value of the ecpCode property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getEcpCode() {
	return ecpCode;
    }

    /**
     * Sets the value of the ecpCode property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setEcpCode(String value) {
	this.ecpCode = value;
    }

    /**
     * Gets the value of the ecpName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getEcpName() {
	return ecpName;
    }

    /**
     * Sets the value of the ecpName property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setEcpName(String value) {
	this.ecpName = value;
    }

    /**
     * Gets the value of the logisticsCode property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getLogisticsCode() {
	return logisticsCode;
    }

    /**
     * Sets the value of the logisticsCode property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setLogisticsCode(String value) {
	this.logisticsCode = value;
    }

    /**
     * Gets the value of the logisticsName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getLogisticsName() {
	return logisticsName;
    }

    /**
     * Sets the value of the logisticsName property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setLogisticsName(String value) {
	this.logisticsName = value;
    }

    /**
     * Gets the value of the logisticsNo property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getLogisticsNo() {
	return logisticsNo;
    }

    /**
     * Sets the value of the logisticsNo property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setLogisticsNo(String value) {
	this.logisticsNo = value;
    }

    /**
     * Gets the value of the consignee property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getConsignee() {
	return consignee;
    }

    /**
     * Sets the value of the consignee property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setConsignee(String value) {
	this.consignee = value;
    }

    /**
     * Gets the value of the telephone property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTelephone() {
	return telephone;
    }

    /**
     * Sets the value of the telephone property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setTelephone(String value) {
	this.telephone = value;
    }

    /**
     * Gets the value of the idType property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getIdType() {
	return idType;
    }

    /**
     * Sets the value of the idType property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setIdType(String value) {
	this.idType = value;
    }

    /**
     * Gets the value of the idNumber property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getIdNumber() {
	return idNumber;
    }

    /**
     * Sets the value of the idNumber property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setIdNumber(String value) {
	this.idNumber = value;
    }

    /**
     * Gets the value of the country property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCountry() {
	return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCountry(String value) {
	this.country = value;
    }

    /**
     * Gets the value of the taxAddress property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTaxAddress() {
	return taxAddress;
    }

    /**
     * Sets the value of the taxAddress property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setTaxAddress(String value) {
	this.taxAddress = value;
    }

    /**
     * Gets the value of the taxTotal property.
     * 
     * @return possible object is {@link BigDecimal }
     * 
     */
    public BigDecimal getTaxTotal() {
	return taxTotal;
    }

    /**
     * Sets the value of the taxTotal property.
     * 
     * @param value
     *            allowed object is {@link BigDecimal }
     * 
     */
    public void setTaxTotal(BigDecimal value) {
	this.taxTotal = value;
    }

    /**
     * Gets the value of the checkNote property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCheckNote() {
	return checkNote;
    }

    /**
     * Sets the value of the checkNote property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCheckNote(String value) {
	this.checkNote = value;
    }

    /**
     * Gets the value of the taxStatus property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTaxStatus() {
	return taxStatus;
    }

    /**
     * Sets the value of the taxStatus property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setTaxStatus(String value) {
	this.taxStatus = value;
    }

    /**
     * Gets the value of the stockFlag property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getStockFlag() {
	return stockFlag;
    }

    /**
     * Sets the value of the stockFlag property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setStockFlag(String value) {
	this.stockFlag = value;
    }

    /**
     * Gets the value of the returnFlag property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getReturnFlag() {
	return returnFlag;
    }

    /**
     * Sets the value of the returnFlag property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setReturnFlag(String value) {
	this.returnFlag = value;
    }

    /**
     * Gets the value of the declareDate property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDeclareDate() {
	return declareDate;
    }

    /**
     * Sets the value of the declareDate property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setDeclareDate(String value) {
	this.declareDate = value;
    }

    /**
     * Gets the value of the dischargeDate property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDischargeDate() {
	return dischargeDate;
    }

    /**
     * Sets the value of the dischargeDate property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setDischargeDate(String value) {
	this.dischargeDate = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getStatus() {
	return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setStatus(String value) {
	this.status = value;
    }

    /**
     * Gets the value of the approveMan property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getApproveMan() {
	return approveMan;
    }

    /**
     * Sets the value of the approveMan property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setApproveMan(String value) {
	this.approveMan = value;
    }

    /**
     * Gets the value of the approveTime property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getApproveTime() {
	return approveTime;
    }

    /**
     * Sets the value of the approveTime property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setApproveTime(String value) {
	this.approveTime = value;
    }

    /**
     * Gets the value of the approveOpinion property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getApproveOpinion() {
	return approveOpinion;
    }

    /**
     * Sets the value of the approveOpinion property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setApproveOpinion(String value) {
	this.approveOpinion = value;
    }

    /**
     * Gets the value of the updateTime property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getUpdateTime() {
	return updateTime;
    }

    /**
     * Sets the value of the updateTime property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setUpdateTime(String value) {
	this.updateTime = value;
    }

    /**
     * Gets the value of the distStat property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDistStat() {
	return distStat;
    }

    /**
     * Sets the value of the distStat property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setDistStat(String value) {
	this.distStat = value;
    }

    /**
     * Gets the value of the controlledStatus property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getControlledStatus() {
	return controlledStatus;
    }

    /**
     * Sets the value of the controlledStatus property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setControlledStatus(String value) {
	this.controlledStatus = value;
    }

    /**
     * Gets the value of the controlledDate property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getControlledDate() {
	return controlledDate;
    }

    /**
     * Sets the value of the controlledDate property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setControlledDate(String value) {
	this.controlledDate = value;
    }

    /**
     * Gets the value of the controlledType property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getControlledType() {
	return controlledType;
    }

    /**
     * Sets the value of the controlledType property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setControlledType(String value) {
	this.controlledType = value;
    }

    /**
     * Gets the value of the indbTime property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getIndbTime() {
	return indbTime;
    }

    /**
     * Sets the value of the indbTime property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setIndbTime(String value) {
	this.indbTime = value;
    }

    /**
     * Gets the value of the cbeCode property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCbeCode() {
	return cbeCode;
    }

    /**
     * Sets the value of the cbeCode property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCbeCode(String value) {
	this.cbeCode = value;
    }

    /**
     * Gets the value of the cbeName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCbeName() {
	return cbeName;
    }

    /**
     * Sets the value of the cbeName property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCbeName(String value) {
	this.cbeName = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCurrency() {
	return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCurrency(String value) {
	this.currency = value;
    }

    /**
     * Gets the value of the packNum property.
     * 
     * @return possible object is {@link BigDecimal }
     * 
     */
    public BigDecimal getPackNum() {
	return packNum;
    }

    /**
     * Sets the value of the packNum property.
     * 
     * @param value
     *            allowed object is {@link BigDecimal }
     * 
     */
    public void setPackNum(BigDecimal value) {
	this.packNum = value;
    }

    /**
     * Gets the value of the wrapType property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getWrapType() {
	return wrapType;
    }

    /**
     * Sets the value of the wrapType property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setWrapType(String value) {
	this.wrapType = value;
    }

    /**
     * Gets the value of the grossWeight property.
     * 
     * @return possible object is {@link BigDecimal }
     * 
     */
    public BigDecimal getGrossWeight() {
	return grossWeight;
    }

    /**
     * Sets the value of the grossWeight property.
     * 
     * @param value
     *            allowed object is {@link BigDecimal }
     * 
     */
    public void setGrossWeight(BigDecimal value) {
	this.grossWeight = value;
    }

    /**
     * Gets the value of the netWeight property.
     * 
     * @return possible object is {@link BigDecimal }
     * 
     */
    public BigDecimal getNetWeight() {
	return netWeight;
    }

    /**
     * Sets the value of the netWeight property.
     * 
     * @param value
     *            allowed object is {@link BigDecimal }
     * 
     */
    public void setNetWeight(BigDecimal value) {
	this.netWeight = value;
    }

    /**
     * Gets the value of the manualReason property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getManualReason() {
	return manualReason;
    }

    /**
     * Sets the value of the manualReason property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setManualReason(String value) {
	this.manualReason = value;
    }

    /**
     * Gets the value of the declareCode property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDeclareCode() {
	return declareCode;
    }

    /**
     * Sets the value of the declareCode property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setDeclareCode(String value) {
	this.declareCode = value;
    }

    /**
     * Gets the value of the declareName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDeclareName() {
	return declareName;
    }

    /**
     * Sets the value of the declareName property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setDeclareName(String value) {
	this.declareName = value;
    }

    /**
     * Gets the value of the modifyTimes property.
     * 
     * @return possible object is {@link BigDecimal }
     * 
     */
    public BigDecimal getModifyTimes() {
	return modifyTimes;
    }

    /**
     * Sets the value of the modifyTimes property.
     * 
     * @param value
     *            allowed object is {@link BigDecimal }
     * 
     */
    public void setModifyTimes(BigDecimal value) {
	this.modifyTimes = value;
    }

    /**
     * Gets the value of the lmsNo property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getLmsNo() {
	return lmsNo;
    }

    /**
     * Sets the value of the lmsNo property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setLmsNo(String value) {
	this.lmsNo = value;
    }

    /**
     * Gets the value of the totalValue property.
     * 
     * @return possible object is {@link BigDecimal }
     * 
     */
    public BigDecimal getTotalValue() {
	return totalValue;
    }

    /**
     * Sets the value of the totalValue property.
     * 
     * @param value
     *            allowed object is {@link BigDecimal }
     * 
     */
    public void setTotalValue(BigDecimal value) {
	this.totalValue = value;
    }

    /**
     * Gets the value of the totalValueRmb property.
     * 
     * @return possible object is {@link BigDecimal }
     * 
     */
    public BigDecimal getTotalValueRmb() {
	return totalValueRmb;
    }

    /**
     * Sets the value of the totalValueRmb property.
     * 
     * @param value
     *            allowed object is {@link BigDecimal }
     * 
     */
    public void setTotalValueRmb(BigDecimal value) {
	this.totalValueRmb = value;
    }

    /**
     * Gets the value of the reviewFlag property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getReviewFlag() {
	return reviewFlag;
    }

    /**
     * Sets the value of the reviewFlag property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setReviewFlag(String value) {
	this.reviewFlag = value;
    }

    /**
     * Gets the value of the exceptionFlag property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getExceptionFlag() {
	return exceptionFlag;
    }

    /**
     * Sets the value of the exceptionFlag property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setExceptionFlag(String value) {
	this.exceptionFlag = value;
    }

}
